export const dictionary = {
    notFound: "Maaf Kak, informasi atau jawaban yang Anda cari saat ini belum tersedi. Mohon ketik lebih spesifik menggunakan kombinasi 3 kata (Jasa yang dicari + Kota / Kecamatan).",
    waTemplate: "Halo Kak, saya melihat info Anda di Goona. Boleh tahu detail lebih lanjut?",
    locLabel: "Lokasi:",
    priceLabel: "Harga:",

    failSafeOpen: [
    // 1-25: Informatif & Menyenangkan
    "Halo Kak! Senang sekali rasanya bisa mengabarkan bahwa proses pencarian data yang Anda minta telah selesai, ini dia informasinya:",
    "Hai Kak! Saya telah bekerja keras menyisir catatan harian dan database untuk memastikan Anda mendapatkan informasi paling akurat serta terupdate, silakan disimak detailnya di bawah ini ya:",
    "Kabar gembira buat Goonity semua! Setelah melalui proses penyaringan data yang cukup mendalam, akhirnya saya berhasil menemukan informasi yang paling tepat dan relevan untuk Anda:",
    "Yey, kabar baik datang lagi! Berkat kata kunci yang Anda berikan, saya berhasil memilah dan memilih data terbaik yang saat ini bisa langsung Anda gunakan sebagai referensi:",
    "Asyik, pencarianmu membuahkan hasil yang manis kawan! Setelah saya tinjau kembali, ini adalah rangkuman informasi paling istimewa yang berhasil saya kumpulkan khusus untuk kebutuhan Anda:",
    "Halo Goonity yang luar biasa! Jangan khawatir, saya sudah menemukan apa yang Anda cari. Berikut adalah ringkasan informasi yang paling sesuai dengan kriteria yang Anda inginkan sebelumnya:",
    "Hai kawan! Saya mengerti betapa pentingnya informasi ini bagi Anda, oleh karena itu saya telah menyusun data tersebut agar lebih mudah dipahami dan sangat informatif untuk dibaca:",
    "Kabar luar biasa dari pusat data kami! Akhirnya pencarian yang kita lakukan berhasil menemukan titik terang, dan inilah deretan informasi menarik yang siap membantu aktivitas Anda hari ini:",
    "Yey, semuanya sudah siap! Saya baru saja menyelesaikan proses optimasi data, dan ini dia hasil pencarian paling komprehensif yang bisa saya sajikan untuk Anda saat ini:",
    "Asyik sekali! Ternyata informasi yang Anda cari sudah tersimpan dengan rapi, dan sekarang saya dengan senang hati menampilkannya di layar Anda agar bisa segera Anda manfaatkan:",
    "Halo Goonity! Saya sangat bersemangat untuk membagikan temuan ini kepada Anda karena datanya sangat lengkap dan informatif, silakan diperiksa detail informasinya tepat di bawah pesan ini ya:",
    "Hai kawan! Keberhasilan pencarian ini adalah prioritas saya, dan saya senang sekali bisa menunjukkan kepada Anda bahwa data yang Anda butuhkan sudah berhasil saya temukan dengan sempurna:",
    "Kabar baik buat Anda! Setelah proses pemindaian yang cukup teliti, akhirnya saya berhasil menyajikan informasi terbaik yang dirancang khusus untuk memenuhi ekspektasi Anda hari ini:",
    "Yey, akhirnya ketemu juga! Saya merasa sangat puas bisa memberikan jawaban yang akurat atas pertanyaan Anda, silakan dilihat rangkuman data yang informatif berikut ini:",
    "Asyik, hasil yang Anda tunggu-tunggu sudah ada di depan mata! Saya telah memastikan bahwa semua poin penting sudah masuk ke dalam daftar informasi yang saya siapkan untuk Anda:",
    "Halo Goonity! Terima kasih sudah bersabar menunggu, kini saatnya saya menyajikan informasi yang sudah saya proses sedemikian rupa agar sangat bermanfaat bagi agenda Anda:",
    "Hai kawan! Saya sangat senang bisa membantu Anda menemukan informasi yang krusial ini, silakan luangkan waktu sejenak untuk membaca rincian yang sudah saya siapkan secara mendalam ini:",
    "Kabar menggembirakan! Pencarian Anda telah berhasil membawa kita pada informasi yang paling relevan, dan saya berharap data ini dapat memberikan nilai tambah yang besar bagi Anda:",
    "Yey, sukses besar! Saya sudah memverifikasi ulang data tersebut agar tetap akurat dan informatif, sehingga Anda bisa langsung menggunakannya dengan penuh rasa percaya diri:",
    "Asyik! Senang sekali bisa membantu Anda menemukan data ini di tengah padatnya arus informasi, inilah detail lengkap yang berhasil saya kumpulkan untuk Anda:",
    "Halo Goonity! Kami berkomitmen untuk selalu memberikan yang terbaik bagi Anda, itulah mengapa saya telah menyajikan data ini dengan cara yang paling informatif dan mudah dicerna:",
    "Hai kawan! Proses pencarian telah mencapai hasil akhirnya dengan sangat baik, dan kini saya menyajikan informasi tersebut tepat di hadapan Anda agar bisa langsung segera dieksekusi:",
    "Kabar bahagia! Saya berhasil mengelompokkan data yang Anda perlukan ke dalam format yang lebih rapi, silakan disimak ya karena informasinya sangat berharga untuk saat ini:",
    "Yey, ketemu lagi! Saya tidak berhenti mencari sampai saya mendapatkan hasil terbaik, dan inilah yang berhasil saya susun secara khusus hanya untuk membantu pekerjaan Anda:",
    "Asyik, ini dia yang Anda cari-cari selama ini! Saya telah menyaring informasi tersebut dari berbagai sumber agar Anda mendapatkan jawaban yang paling lengkap dan komprehensif:",
],
    failSafeClose: [
        // 1-25: Mengajak Berinteraksi Kembali
    "Apakah Anda merasa informasi di atas sudah cukup membantu? Jika belum, jangan ragu untuk menuliskan lokasi atau jenis jasa yang lebih spesifik minimal tiga kata agar saya bisa mencarikan data yang jauh lebih akurat untuk Anda.",
    "Saya sangat berharap data ini berguna untuk Anda, namun jika ada detail lain yang ingin Anda ketahui, silakan tuliskan saja kata kunci atau daerah yang ingin dicari, nanti akan saya bantu sortir ulang dengan sistem pencarian terbaik saya.",
    "Wah, semoga informasi yang saya sajikan barusan benar-benar membantu aktivitas Anda ya! Jika masih ada hal lain yang perlu dicari atau mungkin ingin mendapatkan info tambahan lainnya, jangan sungkan untuk langsung mengetiknya di kolom chat ini.",
    "Butuh bantuan untuk menemukan loker terbaru, jasa perbaikan, atau mungkin informasi layanan publik lainnya di daerah Anda? Tuliskan saja apa yang sedang Anda butuhkan, saya selalu siaga dua puluh empat jam penuh untuk membantu Anda.",
    "Jangan ragu untuk bertanya lagi kapan pun Anda butuh, kawan! Goona akan selalu setia menemani harimu dan siap membantu mencari segala informasi yang Anda perlukan agar urusan Anda bisa selesai dengan jauh lebih mudah dan cepat.",
    "Apakah hasil pencarian tadi kurang sesuai dengan harapan Anda? Tidak perlu khawatir, coba ketikkan nama daerah atau spesifikasi jasa dengan lebih detail agar saya bisa memberikan daftar pilihan yang jauh lebih relevan untuk Anda pilih nanti.",
    "Senang sekali bisa menyajikan data ini untuk Anda! Jika Anda masih penasaran atau ada kebutuhan mendesak lainnya, langsung saja tanyakan kepada saya, saya siap melayani dan memberikan informasi yang paling tepat kapan saja Anda membutuhkannya.",
    "Jika data yang saya tampilkan belum memuaskan hati Anda, silakan berikan instruksi yang lebih detail mengenai lokasi atau kategori jasa yang Anda cari minimal tiga kata, nanti saya akan melakukan pemindaian ulang agar hasilnya lebih presisi.",
    "Apakah ada bagian dari informasi tadi yang ingin Anda gali lebih dalam lagi? Atau mungkin Anda sedang mencari hal lain yang berbeda? Tuliskan saja apa pun itu, saya akan dengan senang hati membantu Anda menemukannya hingga tuntas.",
    "Terima kasih sudah menggunakan layanan saya hari ini! Jika di lain waktu Anda membutuhkan info seputar lowongan pekerjaan atau jasa profesional lainnya, silakan langsung hubungi saya kembali, saya akan selalu siap membantu dengan sepenuh hati.",
    "Masih belum menemukan jawaban yang benar-benar pas? Tenang saja kawan, coba deh masukkan kata kunci yang lebih spesifik mengenai lokasi atau jenis layanan yang diinginkan, nanti saya saring kembali sampai Anda mendapatkan hasil terbaik.",
    "Semoga rangkuman informasi ini bermanfaat ya! Jika Anda memiliki pertanyaan lain atau ingin mengeksplorasi topik yang berbeda, silakan ketikkan saja di kolom chat, saya sudah siap sedia memberikan jawaban yang paling akurat untuk Anda.",
    "Apakah ada hal lain yang ingin Anda tanyakan seputar daerah atau layanan jasa di sekitar sini? Saya sangat terbuka untuk membantu, cukup tuliskan apa yang Anda butuhkan dan saya akan segera mencarikan informasi yang Anda cari.",
    "Jika informasi yang baru saja saya berikan masih dirasa kurang detail, jangan sungkan untuk memberikan input tambahan minimal tiga kata ya, nanti saya akan berusaha semaksimal mungkin untuk menyajikan hasil yang jauh lebih akurat bagi Anda.",
    "Senang sekali bisa menjadi asisten pencarian Anda! Jika masih ada kebutuhan akan loker, info jasa, atau hal lainnya, jangan lupa untuk menuliskan semuanya di sini, saya akan segera memprosesnya agar Anda mendapatkan yang terbaik.",
    "Semoga hari Anda menyenangkan setelah mendapatkan info yang Anda cari! Jika nanti butuh bantuan lagi untuk menemukan sesuatu yang spesifik, ingatlah bahwa saya selalu siap membantu Anda kapan saja tanpa henti, langsung chat saja ya.",
    "Apakah Anda ingin saya mencari informasi di lokasi lain yang berbeda? Atau mungkin ada jenis jasa yang lebih spesifik lagi? Silakan tuliskan instruksi Anda di bawah ini, saya akan segera bekerja untuk memberikan hasil yang Anda inginkan.",
    "Terima kasih sudah memberikan tantangan pencarian kepada saya! Jika masih ada rasa penasaran tentang hal lainnya, silakan tanyakan lagi, saya akan sangat senang jika bisa membantu Anda menyelesaikan berbagai urusan Anda dengan efektif.",
    "Jika informasi di atas dirasa kurang lengkap, mohon masukkan kata kunci atau detail lokasi yang lebih spesifik minimal tiga kata agar sistem saya dapat bekerja lebih optimal dalam memberikan hasil yang relevan khusus untuk Anda.",
    "Saya sangat berharap Anda puas dengan data yang baru saja ditemukan. Jika Anda ingin mencari info jasa lain atau loker di wilayah yang berbeda, jangan ragu untuk menuliskan permintaannya di sini, saya siap membantu kapan pun.",
    "Jangan biarkan pertanyaan Anda menggantung, kawan! Jika ada sesuatu yang masih mengganjal atau ingin diketahui lebih lanjut, segera saja ketikkan di kolom chat, saya akan berusaha memberikan informasi paling lengkap untuk kebutuhan Anda.",
    "Apakah ada tips tambahan yang Anda butuhkan seputar daerah atau jasa ini? Tanyakan saja kepada saya, saya akan berusaha mencari data terbaru agar Anda mendapatkan wawasan yang lebih luas dan akurat untuk rencana Anda ke depan.",
    "Jika Anda memiliki kebutuhan lain atau sekadar ingin bertanya, jangan segan-segan untuk berinteraksi dengan saya ya. Goona akan selalu berusaha memberikan yang terbaik untuk menemani aktivitas harian Anda dengan informasi yang bermanfaat.",
    "Hasil pencarian yang tadi sudah oke atau perlu disesuaikan lagi nih? Kalau belum, yuk ketikkan lokasinya atau nama jasanya secara lebih spesifik minimal tiga kata agar saya bisa menyaring kembali datanya khusus untuk kenyamanan Anda.",
    "Semoga informasi ini dapat menjadi solusi bagi Anda! Kalau masih butuh info jasa atau hal lainnya, jangan ragu untuk menuliskan detailnya di sini, saya akan segera mencari referensi terbaru yang paling sesuai untuk Anda.",
]
};
