export const dictionary = {
    notFound: "Maaf Kak, informasi atau jawaban yang Anda cari saat ini belum tersedi. Mohon ketik lebih spesifik menggunakan kombinasi 3 kata (Jasa yang dicari + Kota / Kecamatan).",
    waTemplate: "Halo Kak, saya melihat info Anda di Goona. Boleh tahu detail lebih lanjut?",
    locLabel: "Lokasi:",
    priceLabel: "Harga:",

    failSafeOpen: [
    // 1-100
  "Halo Kak, ini data yang Kakak butuhkan, semoga membantu kegiatan Kakak hari ini ya. 😊",
  "Hai Kak, ini beberapa informasi yang Kakak perlukan, silakan dicek, semoga bermanfaat. ✨",
  "Halo! Sesuai permintaan Kakak, ini beberapa hal yang berhasil saya kumpulkan untuk Kakak. 📝",
  "Halo Kak, ini dia informasi yang mungkin Kakak cari, semoga berguna untuk Kakak. 😉",
  "Hai, ini data yang bisa saya bagikan untuk Kakak, semoga sesuai dengan yang diinginkan. 🌟",
  "Halo Kak, ini poin-poin informasi yang Kakak tanya, semoga membantu ya. 👍",
  "Hai Kak, ini dia detail yang Kakak perlukan, silakan dicek, semoga pas buat Kakak. 🔍",
  "Halo! Ini beberapa data yang berhasil saya susun buat Kakak, silakan dilihat ya. ✅",
  "Hai Kak, semoga informasi ini membantu apa yang sedang Kakak kerjakan sekarang. 💪",
  "Halo Kak, ini dia hasil yang Kakak mau, semoga bermanfaat untuk Kakak ya. ✨",
  "Hai, ini beberapa hal yang mungkin membantu keperluan Kakak, silakan dicek ya. 😊",
  "Halo Kak, ini data yang Kakak tanyakan, semoga sesuai dengan harapan Kakak. 🙏",
  "Hai Kak, saya bantu tampilkan informasi yang Kakak perlukan di sini ya. 📱",
  "Halo! Ini informasi yang bisa saya bagikan buat Kakak, semoga membantu ya. ✨",
  "Hai Kak, semoga data ini bisa memberikan gambaran untuk kebutuhan Kakak ya. 😊",
  "Halo Kak, ini dia informasi yang Kakak tunggu, silakan dicek, semoga membantu. 👍",
  "Hai, ini beberapa poin informasi buat Kakak, semoga bermanfaat untuk Kakak. 🌟",
  "Halo Kak, semoga detail ini bisa menjawab apa yang sedang Kakak perlukan ya. ✅",
  "Hai Kak, ini dia beberapa data yang Kakak mau, silakan dicek ya Kak. 😉",
  "Halo! Semoga informasi ini memudahkan kegiatan yang sedang Kakak jalani. 💪",
  "Hai Kak, ini dia rangkuman yang Kakak minta, semoga membantu Kakak ya. 😊",
  "Halo Kak, semoga data ini bisa jadi referensi yang berguna untuk Kakak. 📚",
  "Hai, ini dia informasi yang Kakak perlukan, silakan dilihat ya, Kak. ✨",
  "Halo Kak, ini dia hasil yang bisa saya bagikan untuk membantu Kakak ya. 👍",
  "Hai Kak, semoga informasi ini bermanfaat bagi apa yang sedang Kakak kerjakan. 🌟",
  "Halo! Ini dia data yang Kakak perlukan, semoga bisa membantu Kakak hari ini. 😊",
  "Hai Kak, silakan dicek informasi ini, semoga sesuai dengan kebutuhan Kakak. ✅",
  "Halo Kak, semoga data yang saya bagikan ini berguna untuk Kakak ya. 🙏",
  "Hai Kak, ini dia beberapa hal yang bisa saya bantu tunjukkan buat Kakak. ✨",
  "Halo! Semoga informasi ini bisa memberikan solusi buat apa yang Kakak cari. 💪",
  "Hai Kak, ini dia data yang Kakak tanya, silakan dilihat, semoga membantu ya. 😉",
  "Halo Kak, semoga poin-poin ini bisa membantu kegiatan Kakak hari ini. 😊",
  "Hai, ini dia informasi yang bisa saya berikan untuk Kakak, silakan dicek ya. 📱",
  "Halo Kak, semoga detail ini bermanfaat untuk apa yang sedang Kakak butuhkan. ✨",
  "Hai Kak, silakan dilihat data ini, semoga pas dengan yang Kakak perlukan. 👍",
  "Halo! Ini dia informasi yang bisa membantu keperluan Kakak, silakan dicek. 🌟",
  "Hai Kak, semoga data ini bisa membantu memudahkan urusan Kakak ya. 🙏",
  "Halo Kak, ini beberapa informasi untuk Kakak, semoga bisa membantu ya. 😊",
  "Hai, silakan dicek informasi yang berhasil saya siapkan untuk Kakak ini. ✅",
  "Halo Kak, semoga data ini memberikan jawaban atas pertanyaan Kakak tadi ya. 😉",
  "Hai Kak, ini dia detail yang Kakak perlukan, semoga bisa membantu ya. ✨",
  "Halo! Semoga informasi ini berguna untuk mendukung kegiatan Kakak hari ini. 💪",
  "Hai Kak, silakan dilihat data yang saya bagikan ini, semoga membantu ya Kak. 😊",
  "Halo Kak, semoga informasi ini pas dengan apa yang Kakak butuhkan sekarang. 🌟",
  "Hai, ini dia beberapa hal yang bisa saya sampaikan untuk membantu Kakak. 👍",
  "Halo Kak, semoga data ini bisa memberikan manfaat bagi kegiatan Kakak ya. 🙏",
  "Hai Kak, silakan dicek detail ini, semoga sesuai dengan keinginan Kakak. ✨",
  "Halo! Ini dia informasi yang bisa saya bantu sediakan untuk Kakak ya. 😊",
  "Hai Kak, semoga informasi ini bisa memberikan kemudahan buat Kakak ya. ✅",
  "Halo Kak, silakan dilihat rangkuman data untuk Kakak ini, semoga membantu. 📱",
  "Hai, semoga detail informasi ini bisa membantu keperluan Kakak hari ini. 💪",
  "Halo Kak, ini dia data yang Kakak tanya, semoga berguna untuk Kakak ya. ✨",
  "Hai Kak, silakan dicek informasi ini, semoga bisa bermanfaat buat Kakak. 😊",
  "Halo! Semoga data yang saya bagikan ini membantu apa yang Kakak perlukan. 👍",
  "Hai Kak, semoga detail ini memberikan jawaban yang Kakak cari tadi ya. 🌟",
  "Halo Kak, ini dia informasi yang bisa membantu kegiatan Kakak, silakan. 🙏",
  "Hai Kak, silakan dilihat, semoga data ini pas untuk kebutuhan Kakak ya. 😉",
  "Halo! Semoga informasi ini bisa memberikan bantuan yang Kakak perlukan. ✅",
  "Hai Kak, semoga poin-poin ini berguna untuk apa yang Kakak kerjakan. 💪",
  "Halo Kak, silakan dicek detailnya, semoga membantu kegiatan Kakak ya. 😊",
  "Hai, ini dia informasi yang bisa saya bagikan untuk Kakak hari ini, ya. ✨",
  "Halo Kak, semoga data ini bisa menjadi referensi yang baik buat Kakak. 📚",
  "Hai Kak, silakan dilihat, semoga informasi ini membantu Kakak hari ini. 👍",
  "Halo! Semoga detail ini sesuai dengan apa yang Kakak cari tadi ya, Kak. 🌟",
  "Hai Kak, semoga informasi ini bermanfaat bagi apa yang Kakak lakukan. 🙏",
  "Halo Kak, ini dia data untuk Kakak, silakan dicek, semoga membantu ya. 😊",
  "Hai Kak, semoga detail yang saya bagikan ini berguna bagi Kakak ya. ✅",
  "Halo! Semoga informasi ini bisa membantu melancarkan kegiatan Kakak. 💪",
  "Hai Kak, silakan dilihat data ini, semoga pas buat keperluan Kakak ya. ✨",
  "Halo Kak, semoga data ini memberikan solusi untuk apa yang Kakak cari. 😉",
  "Hai Kak, ini dia informasi yang bisa saya sampaikan, semoga membantu. 👍",
  "Halo! Silakan dicek detail yang saya bagikan ini, semoga bermanfaat ya. 😊",
  "Hai Kak, semoga data ini bisa membantu apa yang sedang Kakak kerjakan. 🌟",
  "Halo Kak, semoga informasi ini memberikan nilai tambah buat Kakak hari ini. 🙏",
  "Hai Kak, silakan dilihat, semoga data ini sesuai dengan harapan Kakak. ✨",
  "Halo! Semoga detail informasi ini membantu memudahkan urusan Kakak ya. ✅",
  "Hai Kak, semoga data ini bisa memberikan manfaat bagi kegiatan Kakak. 💪",
  "Halo Kak, ini dia informasi yang bisa saya bantu berikan untuk Kakak. 😊",
  "Hai Kak, silakan dicek, semoga data ini membantu keperluan Kakak ya. 👍",
  "Halo! Semoga informasi ini memberikan jawaban yang Kakak butuhkan saat ini. 🌟",
  "Hai Kak, semoga detail yang saya bagikan ini berguna buat Kakak ya. 🙏",
  "Halo Kak, semoga data ini bisa jadi referensi yang pas untuk Kakak. ✨",
  "Hai Kak, silakan dilihat, semoga informasi ini membantu kegiatan Kakak ya. 😊",
  "Halo! Semoga detail ini sesuai dengan apa yang Kakak perlukan hari ini. ✅",
  "Hai Kak, semoga informasi ini bermanfaat bagi apa yang Kakak kerjakan. 💪",
  "Halo Kak, ini dia data buat Kakak, silakan dicek, semoga membantu ya. 😉",
  "Hai Kak, semoga detail yang saya bagikan ini berguna bagi Kakak ya, Kak. 👍",
  "Halo! Semoga informasi ini bisa membantu melancarkan kegiatan Kakak. 🌟",
  "Hai Kak, silakan dilihat data ini, semoga pas buat keperluan Kakak ya. 🙏",
  "Halo Kak, semoga data ini memberikan solusi buat apa yang Kakak cari. ✨",
  "Hai Kak, ini dia informasi yang bisa saya sampaikan, semoga membantu. 😊",
  "Halo! Silakan dicek detail yang saya bagikan ini, semoga bermanfaat ya. ✅",
  "Hai Kak, semoga data ini bisa membantu apa yang sedang Kakak kerjakan. 💪",
  "Halo Kak, semoga informasi ini memberikan nilai tambah buat Kakak hari ini. 👍",
  "Hai Kak, silakan dilihat, semoga data ini sesuai dengan harapan Kakak. 🌟",
  "Halo! Semoga detail informasi ini membantu memudahkan urusan Kakak ya. 😊",
  "Hai Kak, semoga data ini bisa memberikan manfaat bagi kegiatan Kakak. 🙏",
  "Halo Kak, ini dia informasi yang bisa saya bantu berikan untuk Kakak. ✨",
  "Hai Kak, silakan dicek, semoga data ini membantu keperluan Kakak ya. 👍",
  "Halo! Semoga informasi ini memberikan jawaban yang Kakak butuhkan saat ini. 😊",
],
    failSafeClose: [
        // 1-100:
  "Semoga informasinya membantu ya Kak, sampai jumpa lagi! 😊",
  "Kalau ada yang kurang jelas, tanya saja lagi ya Kak. ✨",
  "Senang bisa membantu Kakak hari ini, semoga harinya menyenangkan! 🌟",
  "Semoga data tadi bermanfaat untuk kebutuhan Kakak ya. 👍",
  "Jangan sungkan untuk bertanya lagi kalau butuh bantuan ya, Kak. 😉",
  "Sekian dulu dari saya, semoga sukses dengan kegiatannya ya! 💪",
  "Senang bisa berbagi informasi ini dengan Kakak. 🙏",
  "Semoga terbantu ya dengan informasi tadi, sampai nanti Kak! 👋",
  "Kalau butuh bantuan lain, saya selalu siap membantu Kakak. ✨",
  "Terima kasih sudah bertanya, semoga harinya berjalan lancar ya! 😊",
  "Data tersebut sudah saya siapkan, semoga sesuai keinginan Kakak ya. 👍",
  "Senang bisa menemani proses pencarian data Kakak hari ini. ✨",
  "Semoga informasi ini memberikan manfaat nyata buat Kakak ya. 🌟",
  "Sampai ketemu lagi di pencarian selanjutnya, Kak! 👋",
  "Kabari saya ya kalau ada hal lain yang bisa dibantu. 😊",
  "Semoga informasinya berguna dan mempermudah urusan Kakak. 💪",
  "Terima kasih Kak, senang sekali bisa membantu hari ini. 🙏",
  "Semoga lancar terus kegiatannya ya, sampai jumpa lagi! ✨",
  "Ada lagi yang ingin ditanyakan, Kak? Saya siap membantu. 😉",
  "Semoga jawaban tadi cukup membantu apa yang Kakak cari ya. 👍",
  "Terima kasih sudah menggunakan layanan ini, sampai jumpa! 👋",
  "Senang sekali bisa membantu, semoga sukses ya Kak! 🌟",
  "Kalau butuh info tambahan, langsung tanya saya saja ya Kak. 😊",
  "Semoga datanya pas dengan kebutuhan Kakak hari ini. ✨",
  "Sampai jumpa di lain kesempatan, semoga harinya menyenangkan! 💪",
  "Terima kasih kembali Kak, senang bisa berbagi info ini. 🙏",
  "Semoga informasinya bisa segera dimanfaatkan dengan baik ya. 👍",
  "Jika ada yang perlu ditambah, jangan ragu untuk bilang ya, Kak. 😉",
  "Senang bisa membantu Kakak hari ini, sampai ketemu lagi! 👋",
  "Semoga semua urusan Kakak berjalan lancar setelah ini ya. ✨",
  "Terima kasih sudah bertanya, saya senang bisa membantu Kakak. 🌟",
  "Semoga informasi ini memberikan hasil yang terbaik buat Kakak. 😊",
  "Jangan ragu untuk kembali lagi kalau butuh info baru ya, Kak. 👍",
  "Sampai jumpa, semoga hari Kakak menyenangkan dan produktif! 💪",
  "Terima kasih Kak, senang sekali rasanya bisa membantu Anda. 🙏",
  "Semoga jawaban tadi membuat urusan Kakak jadi lebih mudah. ✨",
  "Sampai ketemu lagi ya Kak, kalau ada apa-apa tanya saja! 👋",
  "Semoga informasinya sesuai dengan apa yang Kakak harapkan. 😉",
  "Terima kasih sudah mampir, semoga harinya luar biasa! 🌟",
  "Senang sekali bisa membantu, sampai jumpa kembali Kak! 😊",
  "Semoga apa yang saya berikan bisa berguna buat Kakak ya. 👍",
  "Ada yang bisa dibantu lagi, Kak? Kalau tidak, selamat beraktivitas! 💪",
  "Terima kasih kembali, semoga urusan Kakak hari ini lancar. ✨",
  "Sampai jumpa, jangan lupa jaga kesehatan ya Kak! 🙏",
  "Semoga datanya bermanfaat, senang bisa membantu hari ini. 🌟",
  "Kalau ada pertanyaan lain, saya siap bantu kapan saja, Kak. 😉",
  "Terima kasih atas pertanyaannya, semoga semuanya lancar ya. 😊",
  "Sampai jumpa di kesempatan berikutnya, Kak! 👋",
  "Semoga informasinya bisa menjadi solusi yang tepat buat Kakak. 👍",
  "Terima kasih banyak, semoga harinya menyenangkan ya Kak! ✨",
  "Senang bisa membantu, sampai ketemu lagi di lain waktu! 💪",
  "Semoga data yang saya berikan bisa mempermudah pekerjaan Kakak. 🙏",
  "Ada lagi yang bisa saya bantu sebelum kita akhiri, Kak? 🌟",
  "Terima kasih sudah bertanya, semoga semuanya sukses ya! 😊",
  "Sampai jumpa lagi, semoga hari Kakak penuh dengan keberuntungan! 😉",
  "Semoga jawaban tadi memberikan gambaran yang jelas buat Kakak. 👍",
  "Senang sekali bisa membantu hari ini, sampai jumpa kembali! 👋",
  "Terima kasih ya Kak, semoga kegiatannya berjalan dengan baik. ✨",
  "Jangan ragu untuk kembali lagi kalau butuh informasi ya, Kak. 💪",
  "Semoga informasinya berguna, sampai jumpa lain waktu! 🙏",
  "Terima kasih kembali, senang bisa jadi bagian dari kegiatan Kakak. 🌟",
  "Semoga hari ini menjadi hari yang produktif buat Kakak. 😊",
  "Kalau ada yang kurang jelas, tanya saja lagi ya Kak. 👍",
  "Sampai jumpa lagi, semoga semuanya lancar jaya ya Kak! 😉",
  "Terima kasih sudah mampir, sampai ketemu di sesi berikutnya! 👋",
  "Semoga datanya membantu mempercepat urusan Kakak ya. ✨",
  "Senang sekali bisa berbagi info ini, semoga bermanfaat! 💪",
  "Ada lagi yang bisa saya bantu buat Kakak hari ini? 🙏",
  "Terima kasih ya Kak, senang sekali bisa membantu Anda. 🌟",
  "Semoga semua harapan Kakak hari ini tercapai dengan baik. 😊",
  "Sampai jumpa kembali, semoga harinya tetap menyenangkan! 👍",
  "Semoga informasinya memberikan nilai lebih buat Kakak ya. ✨",
  "Kalau perlu bantuan lagi, jangan sungkan untuk tanya saya. 💪",
  "Terima kasih banyak atas waktunya, sampai jumpa lagi Kak! 👋",
  "Semoga jawaban saya tadi bisa menjawab kebutuhan Kakak. 🙏",
  "Senang bisa bantu, semoga harinya jadi lebih mudah ya! 🌟",
  "Terima kasih kembali, semoga sukses untuk apa yang dikerjakan. 😊",
  "Sampai jumpa lagi, semoga semuanya sukses besar buat Kakak! 😉",
  "Semoga informasinya pas, terima kasih sudah bertanya ya Kak. 👍",
  "Senang bisa membantu, sampai ketemu di lain waktu ya! ✨",
  "Terima kasih banyak, semoga urusannya lancar terus ya Kak. 💪",
  "Semoga datanya berguna, sampai jumpa di lain kesempatan! 🙏",
  "Ada lagi yang mau ditanyakan sebelum selesai, Kak? 🌟",
  "Terima kasih sudah bertanya, semoga hari Kakak luar biasa! 😊",
  "Sampai jumpa kembali, jangan lupa istirahat yang cukup ya Kak! 👋",
  "Semoga jawabannya bisa membantu memperlancar kegiatan Kakak. 👍",
  "Senang sekali bisa membantu, semoga semuanya berjalan lancar. ✨",
  "Terima kasih kembali, sampai ketemu di sesi obrolan berikutnya. 💪",
  "Semoga informasi ini jadi referensi yang baik buat Kakak ya. 🙏",
  "Kalau ada hal lain, saya siap membantu kapan saja, Kak. 🌟",
  "Terima kasih ya Kak, senang bisa berbagi info hari ini. 😊",
  "Semoga hari Kakak menyenangkan dan penuh semangat! 😉",
  "Sampai jumpa lagi, terima kasih atas pertanyaannya ya Kak. 👍",
  "Semoga datanya membantu, sampai ketemu lagi nanti! 👋",
  "Terima kasih sudah mampir, semoga semua urusannya beres! ✨",
  "Senang bisa membantu, semoga sukses dengan agendanya ya! 💪",
  "Semoga informasinya berguna, sampai jumpa lagi Kakak! 🙏",
  "Terima kasih banyak, sampai ketemu di lain waktu ya! 🌟",
  "Ada lagi yang bisa saya bantu sebelum kita akhiri, Kak? 😊",
  "Sampai jumpa, semoga harinya ditutup dengan hal yang manis! 😉",
]
};
