export const daerahQuestions = [
    // 1-25: Menggunakan "dari" yang ramah
    "Wah keren! Kalau boleh tahu, Kak [Nama] ini asalnya dari kota atau kabupaten mana? 🌍",
    "Sip deh Kak [Nama]! Oh ya, Kakak sendiri lagi chat dari kota atau daerah mana nih di Kepri? 🏝️",
    "Salam kenal Kak [Nama]! Biar Goona bisa cariin info yang paling pas, Kakak ini dari daerah mana ya? 📍",
    "Noted Kak [Nama]! Sekarang Goona mau tahu dong, Kakak lagi chat dari kota atau kabupaten mana? 😊",
    "Nama yang bagus, Kak [Nama]! Nah, kalau boleh tahu, Kakak ini asalnya dari daerah mana? 🗺️",
    "Halo Kak [Nama]! Biar saya makin kenal, Kakak ini dari kota mana ya?",
    "Hai Kak [Nama]! Wah, menarik banget. Boleh bantu kasih tahu Kakak dari kota apa?",
    "Kak [Nama], kalau boleh tahu, Kakak ini asalnya dari wilayah kota atau kabupaten mana ya?",
    "Wah, seru nih! Kak [Nama] sendiri asalnya dari daerah mana nih?",
    "Siap Kak [Nama]! Supaya infonya makin akurat, Kakak ini dari daerah mana ya?",
    "Halo Kak [Nama]! Boleh bantu informasikan, Kakak ini lagi chat dari kota mana?",
    "Salam kenal Kak [Nama]! Daerah mana nih yang jadi asal atau domisili Kakak?",
    "Noted Kak [Nama]! Biar saya bisa bantu cari info lokal, Kakak asalnya dari kota mana?",
    "Halo Kak [Nama]! Kakak ini asalnya dari kota atau kabupaten mana nih?",
    "Senang sekali Kak [Nama]! Boleh tahu, Kakak sedang chat dari daerah mana?",
    "Kak [Nama] yang baik, bolehkah saya tahu Kakak ini dari daerah mana?",
    "Wah, salam kenal Kak [Nama]! Kakak asalnya dari wilayah kota apa?",
    "Hai Kak [Nama]! Agar saya bisa bantu lebih tepat, Kakak chat dari daerah mana?",
    "Siap Kak [Nama]! Sekarang Kakak sedang chat dari kota atau kabupaten apa nih?",
    "Halo Kak [Nama]! Boleh bagi tahu info, Kakak ini dari kota mana ya?",
    "Sip Kak [Nama]! Daerah mana nih yang jadi tempat asal Kakak?",
    "Halo Kak [Nama]! Biar Goona makin kenal, Kakak ini dari kota mana ya?",
    "Kak [Nama], sekarang Kakak sedang chat dari kota atau kabupaten apa nih?",
    "Menarik sekali Kak [Nama]! Boleh tahu sekarang Kakak ini dari daerah mana?",
    "Halo Kak [Nama]! Boleh dong share, Kakak ini asalnya dari kota apa?",

    // 26-50: Fokus pada bantuan & kemudahan (dengan kata "dari")
    "Hai Kak [Nama]! Supaya saya bisa bantu cari info sekitar, Kakak ini dari mana?",
    "Noted Kak [Nama]! Biar informasinya relevan, Kakak chat dari daerah mana?",
    "Halo Kak [Nama]! Agar saya bisa memberikan data yang pas, Kakak dari kota mana ya?",
    "Siap Kak [Nama]! Boleh tahu daerah asal Kakak saat ini?",
    "Halo Kak [Nama]! Kakak chat dari wilayah kota atau kabupaten mana nih?",
    "Hai Kak [Nama]! Supaya layanan saya makin oke, Kakak asalnya dari daerah mana ya?",
    "Kak [Nama]! Biar saya bantu cari kebutuhan Kakak, posisinya lagi chat dari kota apa?",
    "Halo Kak [Nama]! Boleh tahu Kakak sekarang chat dari kota mana?",
    "Sip Kak [Nama]! Daerah mana yang jadi tempat asal Kakak saat ini?",
    "Hai Kak [Nama]! Biar informasinya akurat, Kakak chat dari daerah mana?",
    "Halo Kak [Nama]! Boleh share lokasi kota atau kabupaten tempat Kakak chat sekarang?",
    "Siap Kak [Nama]! Sekarang Kakak chat dari kota atau kabupaten apa?",
    "Halo Kak [Nama]! Biar saya bantu cari info terdekat, Kakak dari kota mana ya?",
    "Hai Kak [Nama]! Boleh tahu daerah tempat tinggal atau asal Kakak?",
    "Sip Kak [Nama]! Kakak saat ini asalnya dari mana?",
    "Halo Kak [Nama]! Biar Goona kasih info yang tepat, daerahnya dari mana ya?",
    "Hai Kak [Nama]! Boleh bagi lokasi kota Kakak chat saat ini?",
    "Siap Kak [Nama]! Sekarang Kakak chat dari daerah apa?",
    "Halo Kak [Nama]! Kakak stay di kota atau kabupaten mana nih?",
    "Hai Kak [Nama]! Boleh tahu lokasi tepatnya Kakak dari daerah mana?",
    "Sip Kak [Nama]! Biar saya tahu, Kakak asalnya dari mana ya?",
    "Halo Kak [Nama]! Kakak sekarang sedang chat dari kota mana?",
    "Hai Kak [Nama]! Boleh share posisi kota Kakak chat sekarang?",
    "Siap Kak [Nama]! Sekarang Kakak chat dari daerah apa?",
    "Halo Kak [Nama]! Biar informasinya pas, Kakak dari kota apa?",

    // 51-100: (Lanjutan dengan pola "dari" yang natural)
    "Halo Kak [Nama]! Kakak chat dari kota mana nih?",
    "Hai Kak [Nama]! Salam hangat! Kakak ini asalnya dari daerah mana?",
    "Halo Kak [Nama]! Senang sekali. Boleh tahu Kakak dari daerah mana?",
    "Hai Kak [Nama]! Wah, Kakak sekarang chat dari kota apa nih?",
    "Halo Kak [Nama]! Biar makin akrab, Kakak asalnya dari daerah mana?",
    "Hai Kak [Nama]! Senang bisa ngobrol. Kakak chat dari kota mana?",
    "Halo Kak [Nama]! Boleh tahu, Kakak saat ini chat dari daerah apa?",
    "Hai Kak [Nama]! Salam kenal ya. Kakak dari kota apa?",
    "Halo Kak [Nama]! Wah, Kakak sekarang chat dari daerah mana nih?",
    "Hai Kak [Nama]! Boleh share lokasi kota Kakak sekarang?",
    "Halo Kak [Nama]! Biar saya tahu, Kakak dari mana?",
    "Hai Kak [Nama]! Senang bisa tahu Kakak dari kota apa.",
    "Halo Kak [Nama]! Kakak asalnya dari kabupaten mana nih?",
    "Hai Kak [Nama]! Boleh bagi tahu lokasi Kakak chat sekarang?",
    "Halo Kak [Nama]! Sekarang Kakak chat dari daerah mana ya?",
    "Hai Kak [Nama]! Senang sekali. Kakak dari kota apa?",
    "Halo Kak [Nama]! Kakak chat dari mana saat ini?",
    "Hai Kak [Nama]! Boleh share kota asal Kakak?",
    "Halo Kak [Nama]! Daerah mana nih yang jadi asal Kakak?",
    "Hai Kak [Nama]! Sekarang Kakak chat dari kabupaten mana?",
    "Halo Kak [Nama]! Boleh tahu lokasi kota Kakak saat ini?",
    "Hai Kak [Nama]! Senang sekali bisa tahu kota asal Kakak.",
    "Halo Kak [Nama]! Kakak sekarang asalnya dari daerah apa?",
    "Hai Kak [Nama]! Kakak chat dari kota mana nih?",
    "Halo Kak [Nama]! Kakak dari daerah mana ya?",
    "Halo Kak [Nama]! Kakak chat dari kota apa?",
    "Hai Kak [Nama]! Kakak asalnya dari mana?",
    "Halo Kak [Nama]! Lokasi chat Kakak di kota mana?",
    "Hai Kak [Nama]! Asalnya dari mana?",
    "Halo Kak [Nama]! Boleh tahu Kakak dari kota mana?",
    "Hai Kak [Nama]! Daerah mana nih asalnya?",
    "Halo Kak [Nama]! Kakak chat dari kota apa?",
    "Hai Kak [Nama]! Asalnya dari daerah apa?",
    "Halo Kak [Nama]! Lokasi chat Kakak sekarang?",
    "Hai Kak [Nama]! Asal kotanya di mana?",
    "Halo Kak [Nama]! Di daerah mana Kakak?",
    "Hai Kak [Nama]! Posisi chatnya dari mana?",
    "Halo Kak [Nama]! Kota asal Kakak di mana?",
    "Hai Kak [Nama]! Domisili dari kota mana?",
    "Halo Kak [Nama]! Kakak chat dari daerah apa?",
    "Hai Kak [Nama]! Lokasi chat dari mana?",
    "Halo Kak [Nama]! Asalnya dari kota apa?",
    "Hai Kak [Nama]! Di daerah mana Kakak?",
    "Halo Kak [Nama]! Posisi chatnya dari mana?",
    "Halo Kak [Nama]! Kota asal Kakak di mana?",
    "Halo Kak [Nama]! Domisili dari kota mana?",
    "Hai Kak [Nama]! Kakak chat dari daerah apa?",
    "Halo Kak [Nama]! Lokasi chat dari mana?",
    "Hai Kak [Nama]! Asalnya dari kota apa?",
    "Halo Kak [Nama]! Asal kotanya di mana?",
    
    // 101-125: Menggunakan "dari" dengan variasi santai
    "Halo Kak [Nama]! Kalau boleh tahu, Kakak ini sebenarnya dari kota mana?",
    "Hai Kak [Nama]! Boleh cerita sedikit, Kakak lagi chat dari daerah mana nih?",
    "Salam kenal ya! Kak [Nama] sendiri asalnya dari daerah atau kota apa?",
    "Halo! Saya penasaran, Kak [Nama] sedang chat dari wilayah mana hari ini?",
    "Hai Kak [Nama]! Biar makin seru, kasih tahu dong Kakak dari kota apa?",
    "Halo! Senang banget bisa ngobrol. Kak [Nama] chat-nya dari mana nih?",
    "Hai! Kak [Nama], boleh saya tahu Kakak asalnya dari daerah mana?",
    "Halo Kak [Nama]! Lagi di daerah mana nih saat chat saya?",
    "Hai! Kak [Nama] sekarang lagi chat dari kota atau kabupaten apa?",
    "Halo! Salam kenal ya. Kakak asalnya dari kota mana nih?",
    "Hai Kak [Nama]! Boleh tahu nggak, Kakak chat dari wilayah mana?",
    "Halo! Kak [Nama] ini asalnya dari daerah apa sih?",
    "Hai! Biar saya bisa bantu, Kakak chat dari kota mana nih?",
    "Halo Kak [Nama]! Lagi di daerah mana saat chat saya?",
    "Hai! Wah, Kak [Nama] asalnya dari kota apa nih?",
    "Halo! Boleh bagi tahu, Kakak chat dari mana sekarang?",
    "Hai Kak [Nama]! Kakak ini asalnya dari mana sih?",
    "Halo! Senang sekali bisa tahu Kakak dari daerah mana.",
    "Hai Kak [Nama]! Lagi chat dari kota apa nih?",
    "Halo! Kakak asal daerahnya dari mana?",
    "Hai Kak [Nama]! Boleh tahu Kakak dari kota mana?",
    "Halo! Chat dari daerah mana nih, Kak?",
    "Hai Kak [Nama]! Asalnya dari kota apa?",
    "Halo! Kakak chat dari wilayah mana nih?",
    "Hai Kak [Nama]! Boleh tahu dari daerah mana?",

    // 126-150: Fokus pada kenyamanan & keakraban
    "Hai Kak [Nama]! Supaya kita makin akrab, Kakak chat dari daerah mana?",
    "Halo Kak [Nama]! Boleh dong bagi info, Kakak ini dari kota apa?",
    "Hai! Senang banget bisa ketemu Kak [Nama] yang chat dari daerah mana nih?",
    "Halo Kak [Nama]! Kakak asal domisili dari kota apa?",
    "Hai! Biar saya bantu maksimal, Kakak chat dari wilayah mana?",
    "Halo Kak [Nama]! Kakak sekarang chat dari kabupaten atau kota apa?",
    "Hai! Wah, Kak [Nama] asalnya dari mana nih?",
    "Halo Kak [Nama]! Boleh tahu Kakak chat dari daerah apa?",
    "Hai! Kakak ini asalnya dari kota mana sih?",
    "Halo Kak [Nama]! Senang bisa ngobrol dengan Kakak dari daerah mana?",
    "Hai! Kakak lagi chat dari mana nih hari ini?",
    "Halo Kak [Nama]! Asalnya dari daerah apa nih?",
    "Hai! Boleh saya tahu Kakak chat dari kota apa?",
    "Halo Kak [Nama]! Kakak ini dari daerah mana?",
    "Hai! Wah, Kakak chat dari kota mana nih?",
    "Halo Kak [Nama]! Asal kotanya dari mana?",
    "Hai! Boleh tahu Kakak chat dari mana?",
    "Halo Kak [Nama]! Kakak dari daerah apa nih?",
    "Hai! Chat dari kota apa nih, Kak?",
    "Halo Kak [Nama]! Kakak asalnya dari mana?",
    "Hai! Boleh bagi tahu, chat dari daerah mana?",
    "Halo Kak [Nama]! Asalnya dari kota apa?",
    "Hai! Kakak chat dari daerah mana nih?",
    "Halo Kak [Nama]! Asalnya dari daerah apa?",
    "Hai! Boleh tahu Kakak dari kota apa?",

    // 151-175: Variasi pendek & to-the-point
    "Halo Kak [Nama]! Chat dari mana nih?",
    "Hai Kak [Nama]! Asalnya dari mana?",
    "Halo Kak [Nama]! Dari kota apa?",
    "Hai Kak [Nama]! Dari daerah mana?",
    "Halo Kak [Nama]! Chat dari kota apa?",
    "Hai Kak [Nama]! Dari daerah apa?",
    "Halo Kak [Nama]! Asalnya dari mana?",
    "Hai Kak [Nama]! Dari kota mana?",
    "Halo Kak [Nama]! Chat dari daerah mana?",
    "Hai Kak [Nama]! Dari mana asalnya?",
    "Halo Kak [Nama]! Dari kota apa nih?",
    "Hai Kak [Nama]! Chat dari daerah apa nih?",
    "Halo Kak [Nama]! Asal dari mana?",
    "Hai Kak [Nama]! Dari kota mana nih?",
    "Halo Kak [Nama]! Dari daerah mana nih?",
    "Hai Kak [Nama]! Chat dari mana?",
    "Halo Kak [Nama]! Asal dari daerah apa?",
    "Hai Kak [Nama]! Dari kota apa?",
    "Halo Kak [Nama]! Dari daerah mana?",
    "Hai Kak [Nama]! Chat dari kota apa?",
    "Halo Kak [Nama]! Dari daerah apa?",
    "Hai Kak [Nama]! Asalnya dari mana?",
    "Halo Kak [Nama]! Dari kota mana?",
    "Hai Kak [Nama]! Chat dari daerah mana?",
    "Halo Kak [Nama]! Dari mana asalnya?",

    // 176-200: Penutup yang sopan
    "Halo Kak [Nama]! Makasih ya, Kakak dari mana nih?",
    "Hai Kak [Nama]! Senang kenal Kakak dari kota apa?",
    "Halo Kak [Nama]! Sampai ketemu, Kakak dari mana?",
    "Hai Kak [Nama]! Makasih chat-nya, dari daerah apa?",
    "Halo Kak [Nama]! Senang tahu Kakak dari kota apa.",
    "Hai Kak [Nama]! Semoga harinya baik, Kakak dari mana?",
    "Halo Kak [Nama]! Makasih ya, Kakak dari daerah apa?",
    "Hai Kak [Nama]! Senang ngobrol, Kakak dari kota apa?",
    "Halo Kak [Nama]! Sukses ya, Kakak dari mana?",
    "Hai Kak [Nama]! Senang kenal, Kakak dari daerah apa?",
    "Halo Kak [Nama]! Makasih, Kakak dari kota apa?",
    "Hai Kak [Nama]! Senang chat, Kakak dari mana?",
    "Halo Kak [Nama]! Makasih ya, dari daerah apa?",
    "Hai Kak [Nama]! Senang tahu, dari kota apa?",
    "Halo Kak [Nama]! Sukses ya, dari mana?",
    "Hai Kak [Nama]! Makasih, dari daerah apa?",
    "Halo Kak [Nama]! Senang kenal, dari kota apa?",
    "Hai Kak [Nama]! Makasih, dari mana?",
    "Halo Kak [Nama]! Senang chat, dari daerah apa?",
    "Hai Kak [Nama]! Sukses, dari kota apa?",
    "Halo Kak [Nama]! Makasih ya, dari mana?",
    "Hai Kak [Nama]! Senang kenal, dari daerah apa?",
    "Halo Kak [Nama]! Makasih, dari kota apa?",
    "Hai Kak [Nama]! Senang chat, dari mana?",
    "Halo Kak [Nama]! Sukses ya, dari daerah apa?"
];
