export const daerahQuestions = [
    "Salam kenal Kak [Nama]! Agar saya bisa memberikan rekomendasi info lokal yang paling tepat, kalau boleh tahu Kakak saat ini berdomisili di kota atau kabupaten mana ya?",
    "Halo Kak [Nama]! Senang sekali bisa berkenalan. Supaya saya bisa bantu cari info yang paling relevan dengan area sekitar Kakak, boleh bantu informasikan Kakak sedang berada di daerah mana?",
    "Noted Kak [Nama]! Biar layanan Goona makin maksimal dalam membantu kebutuhan Kakak, kira-kira Kakak saat ini berdomisili atau sedang berada di kota mana ya?",
    "Hai Kak [Nama]! Terima kasih sudah menyapa. Agar saya tidak salah memberikan info, boleh tahu Kakak ini sedang chat dari kota atau kabupaten mana di Kepri?",
    "Salam kenal Kak [Nama]! Untuk membantu saya memberikan update informasi yang sesuai dengan area Kakak, boleh tahu Kakak saat ini tinggal di wilayah mana?",
    "Halo Kak [Nama]! Biar saya bisa jadi asisten yang lebih sigap, Kakak boleh bantu kasih tahu domisili kota atau kabupaten Kakak saat ini tidak?",
    "Sip Kak [Nama]! Supaya Goona bisa kasih info yang benar-benar pas dengan lokasi Kakak, boleh tahu Kakak sekarang sedang ada di daerah mana ya?",
    "Terima kasih Kak [Nama]! Agar saya bisa menyesuaikan informasi dengan kebutuhan lokal Kakak, boleh tahu Kakak berdomisili di mana?",
    "Hai Kak [Nama]! Supaya saya bisa bantu carikan layanan atau info terdekat, boleh bantu informasikan lokasi kota atau kabupaten Kakak saat ini?",
    "Halo Kak [Nama]! Salam kenal ya. Biar saya bisa bantu lebih baik lagi, kira-kira Kakak sedang berada di wilayah kota mana ya saat ini?",
    "Noted Kak [Nama]! Untuk memudahkan saya dalam menyaring informasi yang bermanfaat buat Kakak, boleh tahu Kakak saat ini tinggal di daerah mana?",
    "Halo Kak [Nama]! Senang bisa membantu Kakak hari ini. Supaya info yang saya sajikan akurat, boleh bantu beri tahu Kakak sedang berada di kota apa?",
    "Salam kenal Kak [Nama]! Agar saya bisa memberikan bantuan yang lebih spesifik sesuai wilayah, boleh tahu Kakak saat ini berdomisili di mana?",
    "Sip Kak [Nama]! Agar saya bisa mencarikan info yang paling dekat dengan lokasi Kakak, boleh bantu info kota atau kabupaten tempat Kakak tinggal?",
    "Halo Kak [Nama]! Biar saya makin paham kebutuhan informasi di sekitar Kakak, boleh tahu saat ini Kakak sedang chat dari daerah mana ya?",
    "Terima kasih Kak [Nama]! Supaya saya bisa memberikan rekomendasi yang pas dengan lokasi, Kakak boleh bantu informasikan sedang berada di kota mana?",
    "Hai Kak [Nama]! Biar Goona bisa bantu lebih optimal, bolehkah saya tahu Kakak saat ini tinggal atau berdomisili di wilayah mana?",
    "Halo Kak [Nama]! Senang bisa melayani Kakak. Agar info yang Kakak terima sesuai dengan lokasi, boleh bantu sebutkan kota atau kabupaten Kakak?",
    "Noted Kak [Nama]! Supaya saya tidak salah memberikan rujukan info, Kakak boleh bantu kasih tahu domisili kota Kakak saat ini?",
    "Salam kenal Kak [Nama]! Agar saya bisa membantu Kakak dengan lebih presisi, kira-kira Kakak sedang chat dari kota mana nih?",
    "Halo Kak [Nama]! Biar saya bisa carikan info yang paling relevan dengan area tempat tinggal Kakak, boleh tahu Kakak berada di daerah mana?",
    "Sip Kak [Nama]! Agar saya bisa memberikan layanan yang lebih personal dan tepat sasaran, boleh bantu sebutkan lokasi kota atau kabupaten Kakak?",
    "Terima kasih Kak [Nama]! Untuk keperluan penyajian data informasi yang sesuai dengan lokasi Kakak, boleh tahu Kakak sedang di mana ya?",
    "Hai Kak [Nama]! Agar saya bisa jadi rekan asisten yang lebih baik bagi Kakak, boleh tahu Kakak saat ini berdomisili di kota mana?",
    "Halo Kak [Nama]! Biar info yang Kakak dapatkan lebih akurat dengan kondisi lapangan, boleh bantu saya mengetahui lokasi kota Kakak?",
    "Salam kenal Kak [Nama]! Agar saya bisa memberikan informasi yang pas dengan kebutuhan lokal, Kakak boleh bantu share domisili kotanya?",
    "Noted Kak [Nama]! Biar saya bisa menyaring data yang paling dekat dengan lokasi Kakak, kira-kira Kakak saat ini tinggal di daerah mana ya?",
    "Halo Kak [Nama]! Untuk memudahkan Kakak mendapatkan info yang paling sesuai, boleh tahu Kakak sedang berada di wilayah mana saat ini?",
    "Sip Kak [Nama]! Agar saya bisa membantu mencarikan apa pun dengan lebih relevan, boleh bantu sebutkan kota tempat tinggal Kakak?",
    "Terima kasih Kak [Nama]! Biar saya bisa menyesuaikan isi layanan dengan kebutuhan di daerah Kakak, boleh tahu Kakak di kota apa?",
    "Hai Kak [Nama]! Agar saya bisa memberikan bantuan info yang paling tepat, boleh tahu lokasi kota atau kabupaten Kakak saat ini?",
    "Halo Kak [Nama]! Biar saya makin kenal dengan area layanan saya, Kakak boleh bantu beri tahu sedang chat dari kota mana?",
    "Salam kenal Kak [Nama]! Untuk membantu saya memberikan informasi yang paling bermanfaat, boleh tahu Kakak tinggal di daerah mana?",
    "Noted Kak [Nama]! Supaya saya bisa carikan info yang paling pas dengan wilayah Kakak, boleh tahu domisili Kakak di kota mana?",
    "Halo Kak [Nama]! Biar saya bisa membantu dengan lebih efektif, kira-kira Kakak sedang berada di kota atau kabupaten apa ya?",
    "Sip Kak [Nama]! Agar saya bisa memberikan update info yang paling sesuai dengan lokasi Kakak, boleh bantu sebutkan daerahnya?",
    "Terima kasih Kak [Nama]! Untuk keperluan penyesuaian data info, boleh tahu Kakak sedang berada di wilayah kota mana?",
    "Hai Kak [Nama]! Biar saya bisa jadi asisten yang lebih sigap buat Kakak, boleh bantu informasikan lokasi kota tempat tinggal Kakak?",
    "Halo Kak [Nama]! Salam kenal ya. Supaya saya bisa memberikan layanan yang lebih pas, boleh tahu Kakak saat ini di daerah mana?",
    "Noted Kak [Nama]! Biar saya bisa carikan info lokal yang paling akurat untuk Kakak, kira-kira Kakak saat ini tinggal di mana ya?",
    "Halo Kak [Nama]! Agar saya bisa memberikan data yang lebih spesifik dengan area tempat tinggal Kakak, boleh tahu kota apa ya?",
    "Sip Kak [Nama]! Untuk memastikan info yang Kakak terima sudah sesuai dengan area Kakak, boleh bantu sebutkan kotanya?",
    "Terima kasih Kak [Nama]! Biar saya bisa membantu Kakak dengan lebih tepat, boleh bantu saya mengetahui lokasi kota Kakak saat ini?",
    "Hai Kak [Nama]! Agar saya bisa membantu Kakak menemukan apa pun dengan lebih mudah, boleh tahu Kakak berada di wilayah mana?",
    "Halo Kak [Nama]! Salam kenal. Supaya saya bisa memberikan info yang relevan dengan domisili Kakak, boleh tahu tinggal di mana?",
    "Noted Kak [Nama]! Biar saya bisa menyajikan info yang paling cocok dengan lokasi Kakak, boleh bantu informasikan daerahnya?",
    "Halo Kak [Nama]! Agar saya bisa menjadi asisten yang lebih baik bagi Kakak, boleh tahu Kakak saat ini sedang di kota mana?",
    "Sip Kak [Nama]! Untuk membantu saya memberikan info yang sesuai dengan kebutuhan lokal, boleh bantu sebutkan kota Kakak?",
    "Terima kasih Kak [Nama]! Biar saya bisa memberikan bantuan yang lebih spesifik dengan area Kakak, boleh tahu tinggal di kota apa?",
    "Hai Kak [Nama]! Agar saya bisa menyesuaikan pencarian info dengan lokasi Kakak, boleh bantu saya mengetahui domisili Kakak?"
];
