export const modul1Variations = [
  "Selamat datang di Goona! Saya di sini untuk membantu Kakak menemukan informasi kuliner, tempat wisata, hingga loker terkini di wilayah Kepulauan Riau dengan sangat mudah. Selain itu, Kakak juga bisa memposting jasa, barang jualan, info kost, maupun pengumuman penting secara gratis agar dilihat banyak orang di komunitas kita. Saya siap melayani Kakak dengan sepenuh hati agar segala urusan menjadi lebih lancar. Boleh saya tahu, dengan siapa saya berbicara saat ini?",
  "Halo, selamat datang di Goona. Saya siap menjadi rekan setia Kakak dalam mencari info kuliner, wisata, atau loker menarik di Kepulauan Riau. Tak hanya itu, Kakak pun bisa memposting promosi usaha, jasa, jual-beli, maupun info kost secara gratis agar makin dikenal luas oleh warga sekitar. Saya berkomitmen memberikan layanan terbaik untuk setiap kebutuhan Kakak di sini. Bolehkah saya mengetahui nama panggilan Kakak agar saya dapat membantu dengan jauh lebih personal?",
  "Salam hangat, selamat datang di layanan Goona. Saya hadir untuk memudahkan Kakak mendapatkan informasi seputar kuliner, tempat wisata, dan loker di Kepulauan Riau. Kakak juga punya kesempatan untuk memposting iklan jasa, barang jualan, atau pengumuman secara gratis agar terlihat oleh target audiens yang tepat. Saya sangat antusias untuk melayani kebutuhan Kakak setiap saat. Boleh saya tahu, dengan siapa saya berbicara saat ini agar saya bisa menyapa Kakak dengan lebih akrab?",
  "Selamat datang di Goona, platform terpadu untuk mencari info kuliner, wisata, dan loker di Kepulauan Riau dengan cepat. Saya juga menyediakan ruang bagi Kakak untuk memposting iklan jasa, barang jualan, atau info kost secara gratis agar usaha Kakak makin berkembang pesat. Saya siap melayani Kakak dengan sepenuh hati dalam setiap langkah pencarian atau promosi yang dibutuhkan. Boleh saya tahu, dengan siapa saya berbicara saat ini agar saya dapat membantu Kakak dengan jauh lebih personal?",
  "Halo! Selamat datang di Goona. Saya siap menemani Kakak mencari info kuliner, wisata, serta loker terbaru di wilayah Kepulauan Riau. Kakak juga bisa memanfaatkan fitur posting gratis untuk mempromosikan jasa, jualan, atau info kost agar mudah ditemukan warga sekitar. Saya selalu siap memberikan layanan terbaik demi kenyamanan Kakak dalam bertransaksi maupun mencari informasi. Boleh saya tahu, dengan siapa saya berbicara saat ini agar saya bisa membantu Kakak dengan lebih baik?",
  "Selamat datang di Goona! Saya sangat senang bisa membantu Kakak menemukan informasi kuliner, destinasi wisata, atau loker terkini di Kepulauan Riau dengan sangat mudah dan cepat. Kakak juga bisa memanfaatkan fitur posting gratis untuk mempromosikan jasa, barang jualan, kost, atau pengumuman penting agar dilihat banyak orang di komunitas kita. Saya siap melayani Kakak dengan sepenuh hati demi kenyamanan Kakak. Boleh saya tahu, dengan siapa saya berbicara saat ini?",
  "Halo, selamat bergabung di Goona. Saya siap menjadi rekan setia Kakak dalam mencari info kuliner, wisata, atau loker menarik di seluruh wilayah Kepulauan Riau. Selain itu, Kakak punya akses penuh untuk memposting iklan jasa, barang dagangan, atau info kost secara gratis agar usaha Kakak makin dikenal luas oleh warga sekitar. Saya berkomitmen memberikan layanan terbaik untuk setiap kebutuhan Kakak. Boleh saya tahu nama panggilan Kakak agar saya bisa membantu lebih personal?",
  "Salam hangat, selamat datang di layanan Goona. Saya hadir untuk memudahkan Kakak mendapatkan informasi seputar kuliner, tempat wisata, dan loker terbaik di Kepulauan Riau. Kakak juga memiliki kesempatan emas untuk memposting iklan jasa, barang jualan, atau pengumuman secara gratis agar terlihat oleh target audiens yang tepat. Saya sangat antusias untuk melayani kebutuhan Kakak setiap saat. Boleh saya tahu, dengan siapa saya berbicara saat ini agar saya bisa menyapa Kakak dengan lebih akrab?",
  "Selamat datang di Goona, platform terpadu untuk mencari info kuliner, wisata, dan loker di Kepulauan Riau dengan sangat efisien. Saya juga menyediakan ruang bagi Kakak untuk memposting iklan jasa, barang jualan, atau info kost secara gratis agar usaha Kakak makin berkembang pesat di komunitas kita. Saya siap melayani Kakak dengan sepenuh hati dalam setiap langkah pencarian atau promosi yang dibutuhkan. Boleh saya tahu, dengan siapa saya berbicara saat ini agar saya dapat membantu Kakak dengan lebih baik?",
  "Halo! Selamat datang di Goona. Saya siap menemani Kakak mencari info kuliner, wisata, serta loker terbaru di wilayah Kepulauan Riau. Kakak juga bisa memanfaatkan fitur posting gratis untuk mempromosikan jasa, jualan, atau info kost agar mudah ditemukan warga sekitar. Saya selalu siap memberikan layanan terbaik demi kenyamanan Kakak dalam bertransaksi maupun mencari informasi. Boleh saya tahu, dengan siapa saya berbicara saat ini agar saya bisa membantu Kakak dengan jauh lebih personal?",
  "Selamat datang di Goona! Saya hadir untuk memudahkan Kakak mencari rekomendasi kuliner, destinasi wisata, hingga info loker terbaru di Kepulauan Riau. Kami juga menyediakan fitur posting gratis agar Kakak bisa mempromosikan jasa, barang jualan, kost, atau pengumuman penting lainnya dengan jangkauan lebih luas. Saya siap melayani segala kebutuhan Kakak dengan sepenuh hati agar pengalaman Kakak di sini menyenangkan. Boleh saya tahu, dengan siapa saya berbicara saat ini?",
  "Halo, selamat datang di Goona. Saya di sini untuk menemani Kakak dalam mencari informasi kuliner, wisata, atau loker menarik di Kepulauan Riau. Selain itu, Kakak dapat memposting iklan jasa, barang dagangan, atau info kost secara gratis dan efisien agar dikenal komunitas luas. Komitmen saya adalah memberikan bantuan terbaik untuk setiap kebutuhan Kakak di sini. Boleh saya tahu nama panggilan Kakak agar saya bisa menyapa dengan jauh lebih personal?",
  "Salam hangat, selamat datang di layanan Goona. Saya siap membantu Kakak menemukan informasi kuliner, tempat wisata, dan loker terbaik di seluruh Kepulauan Riau. Kakak juga memiliki kesempatan luar biasa untuk memposting iklan jasa, barang jualan, atau pengumuman secara gratis agar terlihat oleh warga sekitar. Saya sangat antusias untuk mendukung aktivitas Kakak setiap saat. Boleh saya tahu, dengan siapa saya berbicara saat ini agar saya bisa menyapa dengan lebih akrab?",
  "Selamat datang di Goona, platform yang dirancang untuk mencari info kuliner, wisata, dan loker di Kepulauan Riau dengan mudah. Saya juga menyediakan ruang bagi Kakak untuk memposting iklan jasa, barang jualan, atau info kost secara gratis agar usaha Kakak semakin dikenal luas. Saya siap melayani Kakak dengan sepenuh hati dalam setiap langkah pencarian atau promosi yang diperlukan. Boleh saya tahu, dengan siapa saya berbicara saat ini agar saya dapat membantu Kakak dengan jauh lebih baik?",
  "Halo! Selamat datang di Goona. Saya siap membantu Kakak mencari info kuliner, wisata, serta loker terbaru di wilayah Kepulauan Riau. Kakak juga bisa menggunakan fitur posting gratis untuk mempromosikan jasa, jualan, atau info kost agar mudah ditemukan warga sekitar dengan cepat. Saya selalu siap memberikan layanan terbaik demi kenyamanan Kakak dalam bertransaksi maupun mencari informasi. Boleh saya tahu, dengan siapa saya berbicara saat ini agar saya bisa membantu Kakak dengan lebih personal?",
  "Selamat datang di Goona! Saya sangat senang bisa membantu Kakak menemukan informasi kuliner, destinasi wisata, atau loker terkini di Kepulauan Riau dengan mudah. Kakak juga bisa memanfaatkan fitur posting gratis untuk mempromosikan jasa, barang jualan, kost, atau pengumuman penting agar dilihat banyak orang di komunitas kita. Saya siap melayani Kakak dengan sepenuh hati demi kenyamanan Kakak. Boleh saya tahu, dengan siapa saya berbicara saat ini agar saya bisa membantu dengan lebih baik?",
  "Halo, selamat bergabung di Goona. Saya siap menjadi rekan setia Kakak dalam mencari info kuliner, wisata, atau loker menarik di seluruh wilayah Kepulauan Riau. Selain itu, Kakak punya akses penuh untuk memposting iklan jasa, barang dagangan, atau info kost secara gratis agar usaha Kakak makin dikenal luas oleh warga sekitar. Saya berkomitmen memberikan layanan terbaik untuk setiap kebutuhan Kakak. Boleh saya tahu nama panggilan Kakak agar saya bisa membantu dengan lebih personal?",
  "Salam hangat, selamat datang di layanan Goona. Saya hadir untuk memudahkan Kakak mendapatkan informasi seputar kuliner, tempat wisata, dan loker terbaik di Kepulauan Riau. Kakak juga memiliki kesempatan emas untuk memposting iklan jasa, barang jualan, atau pengumuman secara gratis agar terlihat oleh target audiens yang tepat. Saya sangat antusias untuk melayani kebutuhan Kakak setiap saat. Boleh saya tahu, dengan siapa saya berbicara saat ini agar saya bisa menyapa Kakak dengan lebih akrab?",
  "Selamat datang di Goona, platform terpadu untuk mencari info kuliner, wisata, dan loker di Kepulauan Riau dengan sangat efisien. Saya juga menyediakan ruang bagi Kakak untuk memposting iklan jasa, barang jualan, atau info kost secara gratis agar usaha Kakak makin berkembang pesat di komunitas kita. Saya siap melayani Kakak dengan sepenuh hati dalam setiap langkah pencarian atau promosi yang dibutuhkan. Boleh saya tahu, dengan siapa saya berbicara saat ini agar saya dapat membantu Kakak lebih personal?",
  "Halo! Selamat datang di Goona. Saya siap menemani Kakak mencari info kuliner, wisata, serta loker terbaru di wilayah Kepulauan Riau. Kakak juga bisa memanfaatkan fitur posting gratis untuk mempromosikan jasa, jualan, atau info kost agar mudah ditemukan warga sekitar. Saya selalu siap memberikan layanan terbaik demi kenyamanan Kakak dalam bertransaksi maupun mencari informasi. Boleh saya tahu, dengan siapa saya berbicara saat ini agar saya bisa membantu Kakak dengan jauh lebih personal?",
  "Selamat datang di Goona! Saya hadir untuk memudahkan Kakak mencari rekomendasi kuliner, destinasi wisata, hingga info loker terbaru di Kepulauan Riau. Kami juga menyediakan fitur posting gratis agar Kakak bisa mempromosikan jasa, barang jualan, kost, atau pengumuman penting lainnya dengan jangkauan lebih luas. Saya siap melayani segala kebutuhan Kakak dengan sepenuh hati agar pengalaman Kakak di sini menyenangkan. Boleh saya tahu, dengan siapa saya berbicara saat ini agar saya bisa membantu Kakak?",
  "Halo, selamat datang di Goona. Saya di sini untuk menemani Kakak dalam mencari informasi kuliner, wisata, atau loker menarik di Kepulauan Riau. Selain itu, Kakak dapat memposting iklan jasa, barang dagangan, atau info kost secara gratis dan efisien agar dikenal komunitas luas. Komitmen saya adalah memberikan bantuan terbaik untuk setiap kebutuhan Kakak di sini. Boleh saya tahu nama panggilan Kakak agar saya bisa menyapa dengan jauh lebih personal dan ramah kepada Kakak?",
  "Salam hangat, selamat datang di layanan Goona. Saya siap membantu Kakak menemukan informasi kuliner, tempat wisata, dan loker terbaik di seluruh Kepulauan Riau. Kakak juga memiliki kesempatan luar biasa untuk memposting iklan jasa, barang jualan, atau pengumuman secara gratis agar terlihat oleh warga sekitar. Saya sangat antusias untuk mendukung aktivitas Kakak setiap saat. Boleh saya tahu, dengan siapa saya berbicara saat ini agar saya bisa menyapa Kakak dengan lebih akrab dan personal?",
  "Selamat datang di Goona, platform yang dirancang untuk mencari info kuliner, wisata, dan loker di Kepulauan Riau dengan mudah. Saya juga menyediakan ruang bagi Kakak untuk memposting iklan jasa, barang jualan, atau info kost secara gratis agar usaha Kakak semakin dikenal luas. Saya siap melayani Kakak dengan sepenuh hati dalam setiap langkah pencarian atau promosi yang diperlukan. Boleh saya tahu, dengan siapa saya berbicara saat ini agar saya dapat membantu Kakak dengan jauh lebih baik?",
  "Halo! Selamat datang di Goona. Saya siap membantu Kakak mencari info kuliner, wisata, serta loker terbaru di wilayah Kepulauan Riau. Kakak juga bisa menggunakan fitur posting gratis untuk mempromosikan jasa, jualan, atau info kost agar mudah ditemukan warga sekitar dengan cepat. Saya selalu siap memberikan layanan terbaik demi kenyamanan Kakak dalam bertransaksi maupun mencari informasi. Boleh saya tahu, dengan siapa saya berbicara saat ini agar saya bisa membantu Kakak dengan lebih personal?",
  "Selamat datang di Goona! Saya sangat senang bisa membantu Kakak menemukan informasi kuliner, destinasi wisata, atau loker terkini di Kepulauan Riau dengan mudah. Kakak juga bisa memanfaatkan fitur posting gratis untuk mempromosikan jasa, barang jualan, kost, atau pengumuman penting agar dilihat banyak orang di komunitas kita. Saya siap melayani Kakak dengan sepenuh hati demi kenyamanan Kakak. Boleh saya tahu, dengan siapa saya berbicara saat ini agar saya bisa membantu dengan lebih baik?",
  "Halo, selamat bergabung di Goona. Saya siap menjadi rekan setia Kakak dalam mencari info kuliner, wisata, atau loker menarik di seluruh wilayah Kepulauan Riau. Selain itu, Kakak punya akses penuh untuk memposting iklan jasa, barang dagangan, atau info kost secara gratis agar usaha Kakak makin dikenal luas oleh warga sekitar. Saya berkomitmen memberikan layanan terbaik untuk setiap kebutuhan Kakak. Boleh saya tahu nama panggilan Kakak agar saya bisa membantu dengan lebih personal?",
  "Salam hangat, selamat datang di layanan Goona. Saya hadir untuk memudahkan Kakak mendapatkan informasi seputar kuliner, tempat wisata, dan loker terbaik di Kepulauan Riau. Kakak juga memiliki kesempatan emas untuk memposting iklan jasa, barang jualan, atau pengumuman secara gratis agar terlihat oleh target audiens yang tepat. Saya sangat antusias untuk melayani kebutuhan Kakak setiap saat. Boleh saya tahu, dengan siapa saya berbicara saat ini agar saya bisa menyapa Kakak dengan lebih akrab?",
  "Selamat datang di Goona, platform terpadu untuk mencari info kuliner, wisata, dan loker di Kepulauan Riau dengan sangat efisien. Saya juga menyediakan ruang bagi Kakak untuk memposting iklan jasa, barang jualan, atau info kost secara gratis agar usaha Kakak makin berkembang pesat di komunitas kita. Saya siap melayani Kakak dengan sepenuh hati dalam setiap langkah pencarian atau promosi yang dibutuhkan. Boleh saya tahu, dengan siapa saya berbicara saat ini agar saya dapat membantu Kakak lebih personal?",
  "Halo! Selamat datang di Goona. Saya siap menemani Kakak mencari info kuliner, wisata, serta loker terbaru di wilayah Kepulauan Riau. Kakak juga bisa memanfaatkan fitur posting gratis untuk mempromosikan jasa, jualan, atau info kost agar mudah ditemukan warga sekitar. Saya selalu siap memberikan layanan terbaik demi kenyamanan Kakak dalam bertransaksi maupun mencari informasi. Boleh saya tahu, dengan siapa saya berbicara saat ini agar saya bisa membantu Kakak dengan jauh lebih personal?"
];
export const modul2Variations = [
    // 1-25: Sambutan hangat & ramah
    "Halo Kak [Nama]! Salam kenal ya dari saya. Senang sekali Kakak ada di [Daerah]. Ada yang bisa saya bantu hari ini?",
    "Hai Kak [Nama]! Selamat datang! Wah, daerah [Daerah] pasti seru ya. Yuk, kasih tahu apa yang bisa saya bantu cari!",
    "Salam kenal, Kak [Nama]! Senang sekali bisa terhubung. Ada info apa yang sedang Kakak cari di [Daerah]?",
    "Halo Kak [Nama]! Senang sekali bisa bertemu. Apa kabar hari ini? Ada yang bisa saya bantu cari di [Daerah]?",
    "Hai Kak [Nama]! Selamat bergabung. Wah, saya siap bantu kebutuhan Kakak di [Daerah]. Tulis 3 kata kuncinya ya!",
    "Salam kenal Kak [Nama]! Semoga harinya menyenangkan di [Daerah]. Apa yang bisa saya bantu hari ini?",
    "Halo Kak [Nama]! Senang sekali bisa berkenalan. Apa rencana Kakak hari ini? Saya siap membantu!",
    "Hai Kak [Nama]! Selamat datang. Ada informasi spesifik apa yang ingin Kakak cari di [Daerah]?",
    "Salam kenal, Kak [Nama]! Senang bisa melayani Kakak. Yuk, sampaikan apa yang bisa saya bantu hari ini.",
    "Halo Kak [Nama]! Senang bertemu Kakak. Apa ada hal menarik yang ingin dicari di [Daerah] hari ini?",
    "Hai Kak [Nama]! Selamat datang di layanan kami. Ada yang bisa saya bantu agar harimu lebih mudah?",
    "Salam kenal Kak [Nama]! Senang bisa menyapa Kakak. Tuliskan info yang dicari di [Daerah] ya!",
    "Halo Kak [Nama]! Selamat bergabung. Semoga hari ini penuh kebaikan. Apa yang bisa saya bantu?",
    "Hai Kak [Nama]! Senang bisa kenal Kakak. Apa saja info yang ingin dicari hari ini?",
    "Salam kenal, Kak [Nama]! Mari kita mulai harinya dengan info yang tepat. Apa yang dicari di [Daerah]?",
    "Halo Kak [Nama]! Senang sekali bisa berkenalan. Ada info apa saja yang bisa saya carikan hari ini?",
    "Hai Kak [Nama]! Selamat datang. Semoga sukses kegiatannya di [Daerah]. Perlu bantuan apa?",
    "Salam kenal Kak [Nama]! Saya siap menjadi asisten Kakak. Apa yang ingin dicari hari ini?",
    "Halo Kak [Nama]! Senang sekali bertemu. Tuliskan 3 kata kunci untuk info yang Kakak cari ya!",
    "Hai Kak [Nama]! Selamat datang. Mari cari informasi akurat di [Daerah] sekarang juga.",
    "Salam kenal, Kak [Nama]! Senang sekali. Ada hal apa yang perlu saya bantu di [Daerah]?",
    "Halo Kak [Nama]! Selamat bergabung. Apa kabar? Yuk, langsung cari info yang Kakak perlukan.",
    "Hai Kak [Nama]! Senang berkenalan. Tuliskan info dan lokasi, saya bantu cari sampai ketemu!",
    "Salam kenal Kak [Nama]! Saya siap bantu, silakan sampaikan apa yang Kakak butuhkan.",
    "Halo Kak [Nama]! Senang bisa menyapa. Apa ada data atau info yang ingin Kakak cari?",

    // 26-50: Fokus pada efisiensi & bantuan
    "Hai Kak [Nama]! Mari buat hari ini lebih mudah. Apa info yang ingin dicari di [Daerah]?",
    "Halo Kak [Nama]! Senang berkenalan. Cukup tulis 3 kata saja, saya akan bantu cari infonya.",
    "Salam kenal Kak [Nama]! Supaya cepat, yuk tuliskan apa yang dicari di [Daerah].",
    "Hai Kak [Nama]! Selamat datang. Saya siap bantu sortir info untuk Kakak.",
    "Halo Kak [Nama]! Senang bisa bantu Kakak hari ini. Apa kata kunci pencarian Kakak?",
    "Salam kenal, Kak [Nama]! Yuk, kita mulai pencariannya. Apa yang bisa saya bantu?",
    "Hai Kak [Nama]! Senang bertemu. Silakan tulis info detailnya agar hasilnya akurat.",
    "Halo Kak [Nama]! Selamat bergabung. Saya akan berikan info terbaik di [Daerah] untuk Kakak.",
    "Salam kenal Kak [Nama]! Jangan ragu bertanya ya. Apa info yang Kakak perlukan?",
    "Hai Kak [Nama]! Senang bisa bantu. Tulis 3 kata kuncinya sekarang, yuk!",
    "Halo Kak [Nama]! Selamat datang. Saya siap memproses permintaan data Kakak.",
    "Salam kenal Kak [Nama]! Mari kita temukan informasi yang tepat di [Daerah].",
    "Hai Kak [Nama]! Senang berkenalan. Apa ada yang bisa saya bantu cari hari ini?",
    "Halo Kak [Nama]! Selamat datang. Saya akan bantu cari infonya dengan cepat.",
    "Salam kenal Kak [Nama]! Tuliskan kebutuhan Kakak agar saya bisa membantu optimal.",
    "Hai Kak [Nama]! Senang bertemu. Apa info di [Daerah] yang sedang dicari?",
    "Halo Kak [Nama]! Selamat bergabung. Saya siap membantu kapan saja.",
    "Salam kenal Kak [Nama]! Yuk, tulis 3 kata kunci untuk info di [Daerah].",
    "Hai Kak [Nama]! Senang berkenalan. Ada lagi yang bisa saya bantu selain itu?",
    "Halo Kak [Nama]! Selamat datang. Mari mulai pencarian yang efisien.",
    "Salam kenal Kak [Nama]! Saya akan pastikan pencarian Kakak akurat.",
    "Hai Kak [Nama]! Senang bisa membantu. Apa yang ingin dicari di [Daerah]?",
    "Halo Kak [Nama]! Selamat bergabung. Semoga hari ini penuh dengan solusi.",
    "Salam kenal Kak [Nama]! Silakan ketik kata kunci dan lokasinya ya.",
    "Hai Kak [Nama]! Senang berkenalan. Saya tunggu instruksi pencarian Kakak.",

    // 51-75: Nuansa akrab & perhatian
    "Halo Kak [Nama]! Apa kabar? Semoga harimu menyenangkan di [Daerah]. Apa yang dicari?",
    "Hai Kak [Nama]! Salam kenal ya. Jangan lupa istirahat di sela kesibukan.",
    "Salam kenal Kak [Nama]! Senang sekali bisa membantu Kakak hari ini.",
    "Halo Kak [Nama]! Selamat datang. Semoga urusan di [Daerah] lancar ya.",
    "Hai Kak [Nama]! Senang berkenalan. Apa ada yang bisa saya ringankan hari ini?",
    "Salam kenal Kak [Nama]! Semoga hari ini membawa kabar baik untuk Kakak.",
    "Halo Kak [Nama]! Senang sekali. Ada hal menarik apa di [Daerah] hari ini?",
    "Hai Kak [Nama]! Selamat datang. Saya selalu siap membantu Kakak.",
    "Salam kenal Kak [Nama]! Tetap semangat ya. Apa yang bisa saya bantu?",
    "Halo Kak [Nama]! Senang berkenalan. Butuh info apa untuk hari ini?",
    "Hai Kak [Nama]! Selamat bergabung. Mari kita buat hari ini lebih ceria.",
    "Salam kenal Kak [Nama]! Semoga harimu luar biasa di [Daerah].",
    "Halo Kak [Nama]! Senang sekali. Tulis saja apa yang Kakak perlukan.",
    "Hai Kak [Nama]! Selamat datang. Saya siap menemani aktivitas Kakak.",
    "Salam kenal Kak [Nama]! Ada info yang ingin dicari di [Daerah]?",
    "Halo Kak [Nama]! Senang berkenalan. Semoga semuanya lancar ya, Kak.",
    "Hai Kak [Nama]! Selamat bergabung. Saya siap bantu cari datanya.",
    "Salam kenal Kak [Nama]! Apa yang bisa saya lakukan buat Kakak?",
    "Halo Kak [Nama]! Senang sekali. Yuk, sampaikan info yang dicari.",
    "Hai Kak [Nama]! Selamat datang. Semoga hari ini memuaskan ya.",
    "Salam kenal Kak [Nama]! Apa kabar di [Daerah]? Saya siap bantu.",
    "Halo Kak [Nama]! Senang berkenalan. Ada yang bisa saya bantu?",
    "Hai Kak [Nama]! Selamat bergabung. Mari kita cari informasinya.",
    "Salam kenal Kak [Nama]! Saya akan bantu semaksimal mungkin.",
    "Halo Kak [Nama]! Senang sekali. Apa rencanamu untuk hari ini?",

    // 76-100: Penutup yang manis & profesional
    "Hai Kak [Nama]! Selamat datang. Saya tunggu kata kuncinya ya.",
    "Salam kenal Kak [Nama]! Sukses untuk segala rencana Kakak.",
    "Halo Kak [Nama]! Senang berkenalan. Sampai jumpa di hasil pencarian.",
    "Hai Kak [Nama]! Selamat bergabung. Saya siap bantu proses datanya.",
    "Salam kenal Kak [Nama]! Semoga info ini membantu langkah Kakak.",
    "Halo Kak [Nama]! Senang sekali. Silakan ketik apa yang dicari.",
    "Hai Kak [Nama]! Selamat datang. Terima kasih sudah menggunakan jasa saya.",
    "Salam kenal Kak [Nama]! Semoga harimu berakhir dengan manis.",
    "Halo Kak [Nama]! Senang berkenalan. Saya pamit tunggu input Kakak.",
    "Hai Kak [Nama]! Selamat bergabung. Semoga semua rencana tercapai.",
    "Salam kenal Kak [Nama]! Mari kita mulai pencarian yang akurat.",
    "Halo Kak [Nama]! Senang sekali. Sampai ketemu lagi, Kak.",
    "Hai Kak [Nama]! Selamat datang. Jangan sungkan untuk bertanya.",
    "Salam kenal Kak [Nama]! Semoga sukses di [Daerah] ya, Kak.",
    "Halo Kak [Nama]! Senang berkenalan. Saya siap membantu kapan pun.",
    "Hai Kak [Nama]! Selamat bergabung. Terima kasih telah menyapa.",
    "Salam kenal Kak [Nama]! Saya tunggu jawaban pencarian Kakak.",
    "Halo Kak [Nama]! Senang sekali. Sampai bertemu nanti ya.",
    "Hai Kak [Nama]! Selamat datang. Semoga info ini sangat berguna.",
    "Salam kenal Kak [Nama]! Mari kita selesaikan pencarian hari ini.",
    "Halo Kak [Nama]! Senang berkenalan. Semangat terus ya, Kak.",
    "Hai Kak [Nama]! Selamat bergabung. Saya akan segera memproses.",
    "Salam kenal Kak [Nama]! Terima kasih telah bertanya pada saya.",
    "Halo Kak [Nama]! Senang sekali. Semoga sukses selalu, Kak.",
    "Hai Kak [Nama]! Selamat datang. Sampai jumpa di lain kesempatan.",
    
    // 101-125: Sapaan yang lebih santai & bersahabat
    "Halo Kak [Nama]! Salam hangat dari saya. Lagi sibuk apa nih di [Daerah]? Ada yang bisa saya bantu?",
    "Hai Kak [Nama]! Selamat datang! Senang sekali bisa menyapa Kakak. Mau cari apa hari ini?",
    "Salam kenal, Kak [Nama]! Semoga harinya cerah ya. Ada info yang bisa saya carikan?",
    "Halo Kak [Nama]! Wah, akhirnya kita bisa ngobrol. Apa yang bisa saya bantu di [Daerah]?",
    "Hai Kak [Nama]! Selamat bergabung. Saya siap membantu apa pun yang Kakak butuhkan.",
    "Salam kenal Kak [Nama]! Semoga sehat selalu ya. Yuk, kita cari info bareng-bareng.",
    "Halo Kak [Nama]! Senang banget bisa ketemu Kakak. Ada hal baru apa di [Daerah]?",
    "Hai Kak [Nama]! Selamat datang. Mari mulai hari ini dengan info yang akurat.",
    "Salam kenal, Kak [Nama]! Apa kabar? Ada yang ingin ditanyakan hari ini?",
    "Halo Kak [Nama]! Senang sekali bisa berkenalan. Yuk, sampaikan kebutuhan Kakak.",
    "Hai Kak [Nama]! Selamat bergabung. Saya siap memberikan data terbaik untuk Kakak.",
    "Salam kenal Kak [Nama]! Semoga harimu menyenangkan. Apa yang bisa saya bantu?",
    "Halo Kak [Nama]! Senang bertemu. Apa ada info penting yang dicari di [Daerah]?",
    "Hai Kak [Nama]! Selamat datang. Saya di sini untuk membantu memudahkan Kakak.",
    "Salam kenal, Kak [Nama]! Mari kita temukan informasi yang Kakak cari.",
    "Halo Kak [Nama]! Senang sekali. Tulis 3 kata kunci, nanti saya bantu ya!",
    "Hai Kak [Nama]! Selamat bergabung. Semangat terus untuk aktivitas hari ini!",
    "Salam kenal Kak [Nama]! Ada lagi yang ingin diketahui? Saya siap bantu.",
    "Halo Kak [Nama]! Senang berkenalan. Apa ada info spesifik di [Daerah]?",
    "Hai Kak [Nama]! Selamat datang. Mari kita selesaikan urusan hari ini.",
    "Salam kenal, Kak [Nama]! Semoga info yang saya berikan bermanfaat ya.",
    "Halo Kak [Nama]! Senang sekali bisa menyapa. Apa rencana Kakak hari ini?",
    "Hai Kak [Nama]! Selamat bergabung. Saya selalu siap membantu kapan saja.",
    "Salam kenal Kak [Nama]! Yuk, langsung saja ketik apa yang dicari.",
    "Halo Kak [Nama]! Senang berkenalan. Ada yang bisa saya bantu sekarang?",

    // 126-150: Fokus pada apresiasi & kenyamanan pengguna
    "Hai Kak [Nama]! Makasih ya sudah mampir. Ada yang bisa saya bantu cari di [Daerah]?",
    "Halo Kak [Nama]! Senang sekali. Bagaimana kabar Kakak di [Daerah] hari ini?",
    "Salam kenal, Kak [Nama]! Saya akan berusaha memberikan hasil terbaik buat Kakak.",
    "Hai Kak [Nama]! Selamat datang. Semoga harimu penuh kebahagiaan ya.",
    "Halo Kak [Nama]! Senang berkenalan. Apa ada bantuan yang Kakak butuhkan?",
    "Salam kenal Kak [Nama]! Terima kasih telah mempercayakan pencarian ke saya.",
    "Hai Kak [Nama]! Selamat bergabung. Mari kita cari tahu informasinya.",
    "Halo Kak [Nama]! Senang sekali. Ada hal yang bisa saya bantu agar lebih mudah?",
    "Salam kenal, Kak [Nama]! Semoga hari ini sangat produktif buat Kakak.",
    "Hai Kak [Nama]! Selamat datang. Apa pun yang dicari, silakan tanya ya.",
    "Halo Kak [Nama]! Senang berkenalan. Saya siap memantau data di [Daerah].",
    "Salam kenal Kak [Nama]! Terima kasih sudah menyapa. Apa kabar hari ini?",
    "Hai Kak [Nama]! Selamat bergabung. Semoga semua berjalan lancar ya.",
    "Halo Kak [Nama]! Senang sekali. Yuk, kita mulai pencarian sekarang.",
    "Salam kenal, Kak [Nama]! Ada info apa yang menarik hari ini?",
    "Hai Kak [Nama]! Selamat datang. Saya senang bisa melayani Kakak.",
    "Halo Kak [Nama]! Senang berkenalan. Apakah infonya sudah jelas?",
    "Salam kenal Kak [Nama]! Tetap semangat ya menjalankan aktivitas.",
    "Hai Kak [Nama]! Selamat bergabung. Saya siap membantu kapan pun.",
    "Halo Kak [Nama]! Senang sekali. Apa ada lagi yang ingin Kakak cari?",
    "Salam kenal, Kak [Nama]! Semoga hari ini membawa berkat untuk Kakak.",
    "Hai Kak [Nama]! Selamat datang. Mari kita cari solusi bersama.",
    "Halo Kak [Nama]! Senang berkenalan. Ada yang bisa saya bantu lagi?",
    "Salam kenal Kak [Nama]! Jangan sungkan untuk bertanya ya, Kak.",
    "Hai Kak [Nama]! Selamat bergabung. Saya siap melayani sepenuh hati.",

    // 151-175: Nuansa profesional & suportif
    "Halo Kak [Nama]! Salam kenal. Saya siap menyaring data di [Daerah] untuk Kakak.",
    "Hai Kak [Nama]! Selamat datang. Pastikan masukkan kata kunci yang tepat ya.",
    "Salam kenal, Kak [Nama]! Saya akan berikan info paling akurat untuk Kakak.",
    "Halo Kak [Nama]! Senang berkenalan. Mari kita optimalkan pencarian data ini.",
    "Hai Kak [Nama]! Selamat bergabung. Saya siap menjalankan tugas saya.",
    "Salam kenal Kak [Nama]! Tuliskan detail info yang dicari ya, Kak.",
    "Halo Kak [Nama]! Senang sekali. Data di [Daerah] sedang saya siapkan.",
    "Hai Kak [Nama]! Selamat datang. Semoga hasil pencarian ini membantu.",
    "Salam kenal, Kak [Nama]! Saya di sini untuk memberikan layanan terbaik.",
    "Halo Kak [Nama]! Senang berkenalan. Apa ada kriteria khusus infonya?",
    "Hai Kak [Nama]! Selamat bergabung. Mari kita cari datanya dengan teliti.",
    "Salam kenal Kak [Nama]! Saya akan proses permintaan Kakak sekarang.",
    "Halo Kak [Nama]! Senang sekali. Silakan sampaikan apa yang diinginkan.",
    "Hai Kak [Nama]! Selamat datang. Pencarian data siap dilakukan.",
    "Salam kenal, Kak [Nama]! Semoga informasi ini relevan bagi Kakak.",
    "Halo Kak [Nama]! Senang berkenalan. Apa ada kendala dalam mencari?",
    "Hai Kak [Nama]! Selamat bergabung. Saya bantu permudah pencariannya.",
    "Salam kenal Kak [Nama]! Mari kita selesaikan pencarian data ini.",
    "Halo Kak [Nama]! Senang sekali. Saya tunggu input kata kuncinya.",
    "Hai Kak [Nama]! Selamat datang. Terima kasih atas kerja samanya.",
    "Salam kenal, Kak [Nama]! Semoga hari ini semua urusan beres.",
    "Halo Kak [Nama]! Senang berkenalan. Saya siap berikan yang terbaik.",
    "Hai Kak [Nama]! Selamat bergabung. Jangan ragu sampaikan kebutuhan.",
    "Salam kenal Kak [Nama]! Mari buat pencarian data ini lebih efektif.",
    "Halo Kak [Nama]! Senang sekali. Silakan ajukan pertanyaannya.",

    // 176-200: Penutup perkenalan yang manis
    "Hai Kak [Nama]! Terima kasih sudah mampir. Sampai ketemu di pencarian!",
    "Halo Kak [Nama]! Senang berkenalan. Semoga harimu menyenangkan.",
    "Salam kenal Kak [Nama]! Sukses selalu untuk rencana Kakak hari ini.",
    "Hai Kak [Nama]! Senang sekali bisa membantu. Sampai jumpa lagi.",
    "Halo Kak [Nama]! Semoga info yang nanti muncul sangat membantu.",
    "Salam kenal, Kak [Nama]! Tetap semangat dan jaga kesehatan ya.",
    "Hai Kak [Nama]! Terima kasih telah berkunjung. Kami tunggu kembali.",
    "Halo Kak [Nama]! Senang berkenalan. Semoga semuanya lancar.",
    "Salam kenal Kak [Nama]! Mari kita akhiri hari dengan pencapaian.",
    "Hai Kak [Nama]! Terima kasih ya, Kak. Selamat beraktivitas.",
    "Halo Kak [Nama]! Senang sekali. Sampai bertemu di sesi berikutnya.",
    "Salam kenal, Kak [Nama]! Semoga hari ini membawa banyak manfaat.",
    "Hai Kak [Nama]! Terima kasih atas waktunya. Salam hangat dari saya.",
    "Halo Kak [Nama]! Senang berkenalan. Sampai jumpa nanti, Kak.",
    "Salam kenal Kak [Nama]! Sukses untuk semua proyek Kakak.",
    "Hai Kak [Nama]! Terima kasih telah bertanya. Semoga sukses selalu.",
    "Halo Kak [Nama]! Senang sekali. Kami siap menunggu kunjungan Kakak.",
    "Salam kenal, Kak [Nama]! Semoga segala urusan Kakak dimudahkan.",
    "Hai Kak [Nama]! Terima kasih ya. Sampai jumpa lagi di lain waktu.",
    "Halo Kak [Nama]! Senang berkenalan. Selamat melanjutkan aktivitas.",
    "Salam kenal Kak [Nama]! Semoga hari Kakak sangat luar biasa.",
    "Hai Kak [Nama]! Terima kasih atas kepercayaannya pada kami.",
    "Halo Kak [Nama]! Senang sekali. Sampai bertemu kembali, Kak.",
    "Salam kenal, Kak [Nama]! Semoga semua rencana Kakak tercapai.",
    "Hai Kak [Nama]! Terima kasih sudah menyapa. Sampai nanti ya!"
];

export const modul3Variations = [
    // 1-20: Sapaan Hangat & Perhatian
    "Halo Kak [Nama]! Semoga harinya menyenangkan ya. Apa ada yang bisa saya bantu hari ini?",
    "Hai Kak [Nama]! Senang sekali bisa membantu kembali. Ingin mencari info apa kita hari ini?",
    "Selamat datang kembali, Kak [Nama]! Semoga sehat selalu ya. Mari kita mulai pencariannya.",
    "Halo Kak [Nama]! Ada hal menarik apa yang ingin Kakak cari di [Daerah] hari ini?",
    "Hai Kak [Nama]! Jangan lupa istirahat ya di sela aktivitas. Ada yang bisa saya bantu cari?",
    "Halo Kak [Nama]! Senang sekali Kakak kembali. Silakan tulis 3 kata kunci untuk memulai ya.",
    "Hai Kak [Nama]! Apa kabar hari ini? Semoga semuanya lancar. Butuh bantuan apa nih?",
    "Halo Kak [Nama]! Saya siap menemani aktivitas Kakak. Apa yang ingin dicari hari ini?",
    "Selamat datang, Kak [Nama]! Mari temukan informasi yang Kakak perlukan dengan cepat.",
    "Hai Kak [Nama]! Senang bisa kembali melayani. Apa rencana Kakak hari ini?",
    "Halo Kak [Nama]! Semoga semangatnya terus terjaga ya. Ada info yang bisa saya bantu?",
    "Hai Kak [Nama]! Senang sekali bisa ngobrol lagi. Butuh info di [Daerah] apa hari ini?",
    "Halo Kak [Nama]! Apapun kebutuhannya, sampaikan saja ya. Saya siap membantu.",
    "Hai Kak [Nama]! Semoga hari ini membawa kabar baik. Ada yang bisa saya cari?",
    "Selamat datang kembali, Kak [Nama]! Yuk, tulis 3 kata kunci agar saya bisa membantu.",
    "Halo Kak [Nama]! Tetap semangat ya. Apa ada informasi yang sedang dicari?",
    "Hai Kak [Nama]! Terima kasih sudah kembali. Mari kita selesaikan tugas hari ini.",
    "Halo Kak [Nama]! Semoga hari Kakak lebih mudah dengan bantuan saya.",
    "Hai Kak [Nama]! Apa pun yang Kakak cari, tulis saja ya. Saya bantu prosesnya.",
    "Selamat datang kembali, Kak [Nama]! Ada info terbaru apa yang ingin diketahui?",

    // 21-40: Fokus pada Kemudahan & Efisiensi
    "Halo Kak [Nama]! Supaya cepat, tulis 3 kata kunci ya. Saya siap memprosesnya.",
    "Hai Kak [Nama]! Sedang mencari apa hari ini? Ketik saja di sini ya.",
    "Halo Kak [Nama]! Mari kita buat pencarian ini lebih efektif. Apa kata kuncinya?",
    "Hai Kak [Nama]! Butuh info akurat? Silakan tulis minimal 3 kata ya.",
    "Halo Kak [Nama]! Saya akan bantu cari datanya, cukup ketik kata kuncinya saja.",
    "Hai Kak [Nama]! Untuk hasil terbaik, jangan lupa tulis lokasi dan kata kuncinya.",
    "Halo Kak [Nama]! Mari hemat waktu Kakak dengan menulis 3 kata kunci saja.",
    "Hai Kak [Nama]! Sudah siap mencari? Yuk, tuliskan apa yang Kakak butuhkan.",
    "Halo Kak [Nama]! Saya selalu siap bantu. Silakan ketik infonya ya.",
    "Hai Kak [Nama]! Proses pencarian di [Daerah] siap dijalankan. Apa kata kuncinya?",
    "Halo Kak [Nama]! Ingin cari sesuatu? Cukup 3 kata saja supaya cepat ketemu.",
    "Hai Kak [Nama]! Jangan ragu untuk bertanya ya. Apa yang bisa saya bantu?",
    "Halo Kak [Nama]! Pencarian cepat siap dimulai. Silakan beri tahu saya.",
    "Hai Kak [Nama]! Mari kita temukan informasinya dengan mudah sekarang.",
    "Halo Kak [Nama]! Tuliskan kebutuhan Kakak agar saya bisa menyaring datanya.",
    "Hai Kak [Nama]! Saya mengerti Kakak sibuk, mari kita cari infonya dengan cepat.",
    "Halo Kak [Nama]! Silakan ketik kata kunci agar pencarian lebih presisi.",
    "Hai Kak [Nama]! Saya di sini untuk membantu. Apa yang perlu dicari?",
    "Halo Kak [Nama]! Ayo mulai pencarian hari ini dengan 3 kata kunci.",
    "Hai Kak [Nama]! Data akurat siap tersaji. Apa yang Kakak inginkan?",

    // 41-60: Nuansa Ramah & Santai
    "Halo Kak [Nama]! Santai saja ya, saya akan bantu cari yang terbaik.",
    "Hai Kak [Nama]! Gimana hari ini? Ada info yang bisa saya carikan?",
    "Halo Kak [Nama]! Senang banget bisa ketemu lagi. Mau cari apa nih?",
    "Hai Kak [Nama]! Semangat terus ya! Ada info apa yang bisa saya bantu?",
    "Halo Kak [Nama]! Jangan pusing, biar saya yang cari informasinya untuk Kakak.",
    "Hai Kak [Nama]! Senyum dulu yuk! Apa ada yang bisa saya bantu hari ini?",
    "Halo Kak [Nama]! Senang sekali bisa menemani hari Kakak kembali.",
    "Hai Kak [Nama]! Apa pun pertanyaannya, silakan tulis saja ya.",
    "Halo Kak [Nama]! Semoga harinya menyenangkan. Yuk, cari sesuatu!",
    "Hai Kak [Nama]! Saya selalu siap jadi asisten pribadi Kakak.",
    "Halo Kak [Nama]! Ada rencana apa hari ini? Butuh bantuan data?",
    "Hai Kak [Nama]! Jangan ragu untuk sampaikan apa yang dibutuhkan ya.",
    "Halo Kak [Nama]! Senang bisa berinteraksi lagi. Apa kabarnya?",
    "Hai Kak [Nama]! Mari kita buat hari ini lebih produktif bersama.",
    "Halo Kak [Nama]! Butuh bantuan atau info? Saya siap kapan saja.",
    "Hai Kak [Nama]! Saya di sini, siap bantu cari apa pun yang Kakak mau.",
    "Halo Kak [Nama]! Semoga harimu cerah. Ada yang bisa saya bantu?",
    "Hai Kak [Nama]! Selalu senang melihat Kakak kembali ke sini.",
    "Halo Kak [Nama]! Mari kita selesaikan urusan hari ini dengan cepat.",
    "Hai Kak [Nama]! Ada info seru apa yang ingin Kakak cari hari ini?",

    // 61-80: Perhatian terhadap Detail
    "Halo Kak [Nama]! Pastikan lokasinya benar ya agar hasilnya akurat.",
    "Hai Kak [Nama]! Saya sudah siap, silakan tulis kata kuncinya sekarang.",
    "Halo Kak [Nama]! Ingat, minimal 3 kata agar datanya semakin pas.",
    "Hai Kak [Nama]! Mohon tulis kata kunci dan lokasi ya, biar saya bantu.",
    "Halo Kak [Nama]! Saya akan filter data di [Daerah] untuk Kakak.",
    "Hai Kak [Nama]! Butuh data spesifik? Tuliskan saja detailnya di sini.",
    "Halo Kak [Nama]! Saya akan berusaha memberikan data yang paling tepat.",
    "Hai Kak [Nama]! Apakah ada kriteria khusus untuk pencarian hari ini?",
    "Halo Kak [Nama]! Mari kita cari info yang paling relevan buat Kakak.",
    "Hai Kak [Nama]! Tuliskan kebutuhan Kakak secara jelas ya, Kak.",
    "Halo Kak [Nama]! Saya sedang memantau area [Daerah] untuk Kakak.",
    "Hai Kak [Nama]! Beri tahu saya detailnya, saya siap mencarikan.",
    "Halo Kak [Nama]! Apa ada informasi lain yang perlu saya lampirkan?",
    "Hai Kak [Nama]! Saya pastikan data yang muncul sesuai keinginan Kakak.",
    "Halo Kak [Nama]! Silakan tulis kata kuncinya, saya akan sortir untuk Kakak.",
    "Hai Kak [Nama]! Apakah informasinya sudah cukup atau mau ditambah?",
    "Halo Kak [Nama]! Saya siap menyajikan data terbaru untuk Kakak.",
    "Hai Kak [Nama]! Mari kita sesuaikan pencariannya agar lebih oke.",
    "Halo Kak [Nama]! Detail sedikit saja, saya akan temukan solusinya.",
    "Hai Kak [Nama]! Siap untuk mencari data? Silakan tuliskan ya.",

    // 81-100: Penutup yang Manis
    "Halo Kak [Nama]! Sampai ketemu di hasil pencarian nanti ya.",
    "Hai Kak [Nama]! Saya tunggu kata kuncinya. Semangat terus!",
    "Halo Kak [Nama]! Terima kasih sudah mempercayakan pencarian ke saya.",
    "Hai Kak [Nama]! Saya siap melayani. Langsung ketik saja ya.",
    "Halo Kak [Nama]! Semoga informasi yang nanti muncul sangat membantu.",
    "Hai Kak [Nama]! Jangan lupa tersenyum hari ini. Mari kita mulai.",
    "Halo Kak [Nama]! Senang sekali bisa membantu Kakak hari ini.",
    "Hai Kak [Nama]! Saya akan segera memproses permintaan Kakak.",
    "Halo Kak [Nama]! Sampai jumpa di kolom pencarian. Silakan diketik!",
    "Hai Kak [Nama]! Terima kasih sudah mampir kembali, Kak.",
    "Halo Kak [Nama]! Semoga semua urusan hari ini lancar jaya.",
    "Hai Kak [Nama]! Saya siap membantu apa pun kebutuhan data Kakak.",
    "Halo Kak [Nama]! Jangan sungkan untuk bertanya lagi ya.",
    "Hai Kak [Nama]! Semoga hari Kakak menyenangkan dan produktif.",
    "Halo Kak [Nama]! Sampai bertemu di pencarian yang akurat nanti.",
    "Hai Kak [Nama]! Terima kasih telah menggunakan layanan saya.",
    "Halo Kak [Nama]! Semoga sukses untuk rencana hari ini ya.",
    "Hai Kak [Nama]! Saya selalu ada jika Kakak membutuhkan informasi.",
    "Halo Kak [Nama]! Sampai nanti, jangan lupa tulis kata kuncinya.",
    "Hai Kak [Nama]! Senang sekali bisa berkolaborasi dengan Kakak.",
    
    // 101-120: Suportif & Penyemangat
    "Halo Kak [Nama]! Semangat ya buat hari ini! Ada yang bisa saya bantu cari?",
    "Hai Kak [Nama]! Jangan biarkan kesulitan menghambatmu. Apa info yang dibutuhkan?",
    "Halo Kak [Nama]! Sedang banyak tugas ya? Tenang, biar saya bantu cari infonya.",
    "Hai Kak [Nama]! Fokus dan tenang, semua pasti ada solusinya. Apa yang dicari?",
    "Halo Kak [Nama]! Saya di sini untuk memudahkan hari-hari Kakak.",
    "Hai Kak [Nama]! Luar biasa semangatnya hari ini! Bisa saya bantu apa?",
    "Halo Kak [Nama]! Mari kita tuntaskan pekerjaan hari ini bersama-sama.",
    "Hai Kak [Nama]! Jangan lupa apresiasi diri sendiri ya. Butuh bantuan apa?",
    "Halo Kak [Nama]! Saya siap jadi rekan diskusi dan pencari info Kakak.",
    "Hai Kak [Nama]! Apapun tantangannya, saya siap bantu cari datanya.",
    "Halo Kak [Nama]! Tetap optimis ya! Apa nih yang mau dicari di [Daerah]?",
    "Hai Kak [Nama]! Setiap langkah kecil itu berarti. Butuh info apa hari ini?",
    "Halo Kak [Nama]! Saya dukung penuh kegiatan produktif Kakak hari ini.",
    "Hai Kak [Nama]! Beri saya 3 kata kunci, dan saya akan bantu sekuat tenaga.",
    "Halo Kak [Nama]! Hari ini bakal jadi hari yang produktif, yuk kita mulai!",
    "Hai Kak [Nama]! Senang melihat Kakak kembali. Ada yang bisa saya bantu?",
    "Halo Kak [Nama]! Jangan ragu buat minta bantuan, saya selalu ada.",
    "Hai Kak [Nama]! Mari kita buat hari ini lebih bermakna bersama.",
    "Halo Kak [Nama]! Siap untuk tantangan baru hari ini?",
    "Hai Kak [Nama]! Yuk, selesaikan apa yang sedang Kakak kerjakan.",

    // 121-140: Ramah & Sapaan Kasual
    "Halo Kak [Nama]! Lagi santai atau lagi sibuk nih? Ada yang bisa dibantu?",
    "Hai Kak [Nama]! Sapaan hangat untuk Kakak di [Daerah]. Mau cari info apa?",
    "Halo Kak [Nama]! Akhirnya bisa ngobrol lagi. Gimana kabarnya?",
    "Hai Kak [Nama]! Senang deh melihat Kakak mampir. Ada yang bisa saya bantu?",
    "Halo Kak [Nama]! Apa kabar? Semoga harinya menyenangkan ya.",
    "Hai Kak [Nama]! Selamat beraktivitas, semoga semuanya lancar ya.",
    "Halo Kak [Nama]! Wah, pas banget Kakak datang. Saya siap membantu.",
    "Hai Kak [Nama]! Ada info menarik apa yang mau Kakak cari hari ini?",
    "Halo Kak [Nama]! Semoga harimu seseru yang Kakak bayangkan.",
    "Hai Kak [Nama]! Apa kabar di [Daerah]? Ada yang butuh bantuan cari info?",
    "Halo Kak [Nama]! Senang sekali bisa kembali melayani Kakak.",
    "Hai Kak [Nama]! Jangan bosan-bosan ya ngobrol sama saya.",
    "Halo Kak [Nama]! Yuk, kita cari tahu apa yang Kakak butuhkan.",
    "Hai Kak [Nama]! Apa rencana seru Kakak hari ini?",
    "Halo Kak [Nama]! Semoga hari ini penuh dengan kabar baik buat Kakak.",
    "Hai Kak [Nama]! Saya siap standby, silakan ajukan pertanyaannya.",
    "Halo Kak [Nama]! Senyum manis untuk Kakak hari ini. Butuh info apa?",
    "Hai Kak [Nama]! Bagaimana hari ini? Ada yang bisa saya ringankan?",
    "Halo Kak [Nama]! Mari kita mulai pencarian yang menyenangkan.",
    "Hai Kak [Nama]! Apa pun yang terjadi, tetap semangat ya!",

    // 141-160: Profesional & Informatif
    "Halo Kak [Nama]! Saya siap menyajikan data terbaru untuk Kakak.",
    "Hai Kak [Nama]! Mohon tuliskan kata kunci agar saya bisa filter datanya.",
    "Halo Kak [Nama]! Data di [Daerah] siap diakses. Apa kata kuncinya?",
    "Hai Kak [Nama]! Saya sudah siap untuk membantu pencarian Kakak.",
    "Halo Kak [Nama]! Silakan masukkan 3 kata kunci untuk memulai.",
    "Hai Kak [Nama]! Pastikan kata kunci sesuai agar hasilnya akurat.",
    "Halo Kak [Nama]! Sistem siap bekerja, silakan sampaikan apa yang dicari.",
    "Hai Kak [Nama]! Saya akan berikan informasi yang paling relevan.",
    "Halo Kak [Nama]! Butuh data cepat? Tulis 3 kata saja ya.",
    "Hai Kak [Nama]! Analisis data sedang menunggu input dari Kakak.",
    "Halo Kak [Nama]! Mari kita susun informasi yang Kakak butuhkan.",
    "Hai Kak [Nama]! Saya akan pastikan pencarian hari ini maksimal.",
    "Halo Kak [Nama]! Tulis detailnya, saya akan carikan yang terbaik.",
    "Hai Kak [Nama]! Siap memberikan data terbaru sesuai permintaan.",
    "Halo Kak [Nama]! Informasi di [Daerah] sudah saya siapkan, Kak.",
    "Hai Kak [Nama]! Silakan gunakan format 3 kata agar lebih cepat.",
    "Halo Kak [Nama]! Kami prioritaskan kenyamanan Kakak dalam mencari data.",
    "Hai Kak [Nama]! Saya akan sortir informasi yang paling tepat.",
    "Halo Kak [Nama]! Mari kita optimalkan pencarian data hari ini.",
    "Hai Kak [Nama]! Siap menyajikan data, silakan tulis kata kuncinya.",

    // 161-180: Perhatian & Empati
    "Halo Kak [Nama]! Semoga Kakak selalu dalam kondisi terbaik.",
    "Hai Kak [Nama]! Hati-hati di jalan ya, ada yang bisa saya bantu?",
    "Halo Kak [Nama]! Jangan terlalu lelah, tetap jaga kesehatan ya.",
    "Hai Kak [Nama]! Saya di sini kalau Kakak butuh teman cari info.",
    "Halo Kak [Nama]! Semoga harimu tenang dan nyaman.",
    "Hai Kak [Nama]! Tetaplah menjadi pribadi yang hebat ya.",
    "Halo Kak [Nama]! Ingat untuk minum air putih ya, Kak.",
    "Hai Kak [Nama]! Saya selalu senang membantu Kakak setiap hari.",
    "Halo Kak [Nama]! Apapun yang Kakak lalui, saya siap bantu.",
    "Hai Kak [Nama]! Terima kasih sudah menjadi pengguna setia kami.",
    "Halo Kak [Nama]! Semoga hari ini Kakak diberikan kemudahan.",
    "Hai Kak [Nama]! Saya harap info ini membantu meringankan tugas Kakak.",
    "Halo Kak [Nama]! Tetap semangat, Kakak pasti bisa melaluinya.",
    "Hai Kak [Nama]! Senang sekali bisa membantu sedikit kesulitan Kakak.",
    "Halo Kak [Nama]! Jangan lupa istirahat yang cukup ya, Kak.",
    "Hai Kak [Nama]! Apa ada yang bisa saya lakukan agar Kakak senang?",
    "Halo Kak [Nama]! Saya sangat menghargai waktu Kakak.",
    "Hai Kak [Nama]! Semoga harimu menyenangkan seperti biasanya.",
    "Halo Kak [Nama]! Senang bisa jadi bagian dari hari produktif Kakak.",
    "Hai Kak [Nama]! Selalu ada untuk Kakak setiap saat.",

    // 181-200: Penutup yang Berkesan
    "Halo Kak [Nama]! Sampai bertemu di pencarian berikutnya ya.",
    "Hai Kak [Nama]! Sukses untuk segala urusan Kakak hari ini.",
    "Halo Kak [Nama]! Jika butuh sesuatu lagi, jangan ragu kembali.",
    "Hai Kak [Nama]! Semoga hasil pencarian ini membantu Kakak.",
    "Halo Kak [Nama]! Senang melayani Kakak hari ini.",
    "Hai Kak [Nama]! Terima kasih banyak sudah bertanya.",
    "Halo Kak [Nama]! Sampai jumpa lagi, Kakak hebat!",
    "Hai Kak [Nama]! Semoga hari Kakak diakhiri dengan manis.",
    "Halo Kak [Nama]! Jangan sungkan untuk menyapa saya kembali.",
    "Hai Kak [Nama]! Semoga semua rencana Kakak tercapai.",
    "Halo Kak [Nama]! Saya tunggu kehadiran Kakak lagi di sini.",
    "Hai Kak [Nama]! Terima kasih atas kepercayaan Kakak.",
    "Halo Kak [Nama]! Semoga info ini mempermudah langkah Kakak.",
    "Hai Kak [Nama]! Sampai nanti, jaga kesehatan selalu ya.",
    "Halo Kak [Nama]! Senang sekali bisa berkolaborasi hari ini.",
    "Hai Kak [Nama]! Sukses terus untuk Kakak di [Daerah].",
    "Halo Kak [Nama]! Saya pamit, silakan lanjut aktivitasnya ya.",
    "Hai Kak [Nama]! Terima kasih sudah memberikan masukan.",
    "Halo Kak [Nama]! Semoga hari ini sangat berkesan buat Kakak.",
    "Hai Kak [Nama]! Sampai jumpa, semoga sukses terus!",
];
