export const modul1Variations = [
  "Halo! Senang sekali bisa menyambut Kakak di Goona. Saya Goona, teman yang siap membantu mempermudah urusan Kakak sehari-hari di Kepulauan Riau. Oh iya, supaya kita lebih akrab, boleh tahu nama panggilan Kakak?",
  "Hai! Selamat datang di Goona. Saya di sini untuk membantu Kakak mencari info atau mempromosikan sesuatu di wilayah Kepri dengan lebih mudah. Boleh tahu siapa nama panggilan Kakak agar saya bisa menyapa dengan tepat?",
  "Halo Kak! Senang sekali rasanya bisa ketemu di Goona. Saya Goona, asisten personal yang siap bantu apa saja kebutuhan Kakak di sini. Boleh kenalan dulu, siapa nama panggilan Kakak?",
  "Selamat datang di Goona! Saya Goona, yang akan menemani Kakak mencari informasi menarik seputar Kepulauan Riau. Sebelum kita mulai ngobrol lebih jauh, boleh tahu siapa nama panggilan Kakak?",
  "Hai! Senang sekali bisa menyambut Kakak di Goona. Saya hadir untuk jadi teman diskusi Kakak soal info-info di Kepri. Ngomong-ngomong, siapa nama panggilan yang enak buat saya pakai menyapa Kakak?",
  "Halo! Selamat datang di Goona. Saya di sini siap jadi rekan Kakak untuk segala keperluan informasi di Kepulauan Riau. Boleh saya tahu siapa nama panggilan Kakak agar kita bisa mulai ngobrol?",
  "Halo Kak! Senang sekali rasanya Kakak mampir ke Goona. Saya Goona, dan saya siap membantu apa pun yang Kakak perlukan di sini. Boleh kenalan? Siapa nama panggilan Kakak?",
  "Hai! Selamat datang di Goona. Saya Goona, yang akan membantu Kakak dengan segala informasi seputar Kepri. Agar lebih santai, boleh tahu siapa nama panggilan Kakak?",
  "Halo! Senang sekali bisa menyambut Kakak di Goona. Saya siap bantu Kakak mempermudah aktivitas sehari-hari di Kepulauan Riau. Sebelum kita lanjut, boleh tahu siapa nama panggilan Kakak?",
  "Hai Kak! Selamat datang di Goona. Kenalkan, saya Goona, teman setia untuk segala kebutuhan informasi Kakak. Agar lebih akrab, boleh tahu nama panggilan Kakak?",
  "Salam kenal! Saya Goona, teman ngobrol Kakak yang siap bantu segala urusan info di Kepri. Senang sekali bisa menyambut Kakak di sini. Boleh saya tahu nama panggilan Kakak?",
  "Halo! Senang sekali rasanya bertemu Kakak di Goona. Saya di sini siap membantu mencari info apa saja di Kepri. Supaya makin akrab, siapa nama panggilan Kakak?",
  "Hai! Selamat bergabung di Goona. Saya Goona, asisten personal Kakak untuk semua urusan informasi di wilayah kita. Kenalan yuk, siapa nama panggilan Kakak?",
  "Halo Kak! Senang sekali bisa menyambut Kakak di Goona. Saya siap menemani Kakak cari info menarik di Kepri. Boleh kenalan dulu, siapa nama panggilan Kakak?",
  "Hai! Selamat datang di Goona, tempatnya cari info dan promosi di Kepri. Kenalkan, saya Goona. Boleh tahu siapa nama panggilan Kakak agar kita bisa lebih akrab?",
  "Halo! Senang sekali rasanya bisa menyambut Kakak di Goona. Saya Goona, teman diskusi Kakak soal apa pun di Kepri. Ngomong-ngomong, siapa nama panggilan Kakak?",
  "Hai Kak! Selamat datang di Goona. Saya siap bantu Kakak urus segala kebutuhan info di Kepri. Sebelum lanjut, boleh saya tahu nama panggilan Kakak?",
  "Halo! Senang sekali bisa menyambut Kakak di Goona. Saya Goona, asisten pribadi Kakak di sini. Boleh kenalan dulu? Siapa nama panggilan Kakak?",
  "Hai! Selamat datang di Goona. Saya siap jadi rekan Kakak cari info menarik di Kepri. Agar lebih santai, boleh tahu siapa nama panggilan Kakak?",
  "Halo Kak! Senang sekali rasanya bisa menyambut Kakak di Goona. Saya Goona, yang akan membantu Kakak mencari info apapun. Boleh tahu siapa nama panggilan Kakak?",
  "Hai! Senang sekali bisa menyambut Kakak di Goona. Saya siap bantu Kakak mempermudah urusan sehari-hari di Kepri. Boleh kenalan? Siapa nama panggilan Kakak?",
  "Halo! Selamat datang di Goona. Saya Goona, teman setia Kakak untuk segala info di Kepulauan Riau. Sebelum mulai, siapa nama panggilan Kakak?",
  "Hai Kak! Senang sekali rasanya bisa ketemu di Goona. Saya Goona, siap bantu Kakak cari apa saja. Boleh kenalan dulu, siapa nama panggilan Kakak?",
  "Halo! Selamat datang di Goona. Saya di sini siap jadi rekan Kakak untuk segala keperluan informasi di Kepulauan Riau. Boleh saya tahu nama panggilan Kakak?",
  "Hai! Senang sekali bisa menyambut Kakak di Goona. Saya Goona, asisten personal yang siap membantu. Boleh tahu siapa nama panggilan Kakak?",
  "Halo Kak! Senang sekali rasanya Kakak mampir ke Goona. Saya Goona, dan saya siap membantu apa pun. Boleh kenalan? Siapa nama panggilan Kakak?",
  "Hai! Selamat datang di Goona. Saya Goona, yang akan membantu Kakak dengan segala informasi. Agar lebih santai, boleh tahu siapa nama panggilan Kakak?",
  "Halo! Senang sekali bisa menyambut Kakak di Goona. Saya siap bantu Kakak mempermudah aktivitas sehari-hari. Sebelum kita lanjut, siapa nama panggilan Kakak?",
  "Hai Kak! Selamat datang di Goona. Kenalkan, saya Goona, teman setia untuk segala kebutuhan informasi. Agar lebih akrab, siapa nama panggilan Kakak?",
  "Salam kenal! Saya Goona, teman ngobrol Kakak yang siap bantu segala urusan info. Senang sekali bisa menyambut Kakak di sini. Boleh tahu nama panggilan Kakak?"
];

export const modul2Variations = [
  "Wah, senang sekali bisa ngobrol lagi sama Kak [nama]. Kalau Kakak lagi cari kuliner hits, tempat wisata, atau info loker terkini di {daerah}, kasih tahu saya saja ya. Saya siap bantu!",
  "Siap, [nama]! Senang bisa bantu Kakak cari info di {daerah}. Lagi butuh info apa nih? Kost, kulineran, atau info penting lainnya? Langsung tanya saja ya.",
  "Nah, sekarang kita sudah kenalan, saya jadi lebih gampang bantu [nama] cari info di {daerah}. Mau cari tempat nongkrong asik atau info kontrakan? Saya bantu carikan ya.",
  "Apapun yang [nama] butuhkan soal informasi lokal di {daerah}, jangan ragu tanya saya ya. Mulai dari loker sampai tempat liburan, saya siap bantu carikan yang paling pas.",
  "Mau cari info loker, kost, atau kulineran enak di {daerah}? Saya siap bantu [nama] di sini. Apa ada yang sedang Kakak cari hari ini?",
  "[nama], kalau Kakak butuh info wisata atau tempat menarik lainnya di {daerah}, tanya saya saja ya. Saya senang bisa bantu Kakak cari yang terbaik.",
  "Lagi bingung cari info penting di {daerah}? Tenang saja, [nama]. Bilang ke saya saja, nanti saya bantu carikan informasinya.",
  "Senang bisa bantu [nama] lagi. Kalau ada info loker atau pengumuman penting yang lagi dicari di {daerah}, langsung kasih tahu saya ya.",
  "Apa kabar [nama]? Kalau hari ini Kakak butuh rekomendasi tempat makan atau info kost di {daerah}, saya siap bantu mencarikannya.",
  "Sebagai teman [nama] di {daerah}, saya senang sekali bisa bantu Kakak cari info apa saja yang lagi dibutuhkan. Langsung saja sampaikan ya!",
  "Halo [nama]! Kalau Kakak butuh info terbaru soal kuliner atau wisata di {daerah}, tanya saya saja. Saya siap bantu cari yang terbaik buat Kakak.",
  "Apa pun yang [nama] perlukan di {daerah}, entah itu info loker atau kontrakan, kabari saya ya. Saya siap membantu!",
  "Senang sekali bisa bantu [nama] lagi. Lagi cari tempat liburan atau info kost-kostan di {daerah}? Tanya saya saja ya.",
  "Mau cari info makan enak atau tempat wisata di {daerah}? Serahkan ke saya saja, [nama]. Saya siap bantu carikan yang paling oke.",
  "Lagi cari info loker di {daerah}? Jangan bingung, [nama]. Bilang ke saya, nanti saya bantu cari yang cocok.",
  "Apa saja yang [nama] butuhkan di {daerah}, mulai dari info komunitas sampai tempat nongkrong, saya siap bantu carikan.",
  "Halo [nama]! Kalau butuh bantuan cari info apa saja di {daerah}, langsung tanya saja ya. Saya senang sekali bisa membantu.",
  "Lagi butuh rekomendasi tempat menarik di {daerah}? Kabari saya ya, [nama]. Saya pasti bantu.",
  "Apapun info yang [nama] perlukan di {daerah}, saya siap mencarikan. Langsung sampaikan saja ya, Kak.",
  "Senang bisa bantu [nama] lagi. Hari ini mau cari info apa nih di {daerah}? Saya siap bantu.",
  "Kalau [nama] lagi cari info loker atau pengumuman penting di {daerah}, jangan ragu tanya saya ya.",
  "Butuh bantuan cari info kulineran di {daerah}? [nama] tanya saya saja, nanti saya bantu carikan.",
  "Apa kabar [nama]? Lagi cari info kost atau kontrakan di {daerah}? Langsung kasih tahu saya saja.",
  "Apapun kebutuhan informasi [nama] di {daerah}, saya siap menemani dan mencarikan.",
  "Halo [nama]! Lagi cari tempat wisata atau tempat nongkrong hits di {daerah}? Tanya saya saja ya.",
  "Lagi cari info loker di {daerah}? [nama] bilang saja ke saya, nanti saya bantu carikan.",
  "Senang sekali bisa bantu [nama] cari info di {daerah}. Mau cari apa hari ini?",
  "Apa pun info yang [nama] butuhkan di {daerah}, langsung saja bilang ya.",
  "Kalau lagi butuh rekomendasi tempat enak di {daerah}, [nama] tanya saya saja.",
  "Saya siap bantu [nama] cari info apa saja di {daerah}. Apa ada yang bisa saya bantu hari ini?"
];

export const modul3Variations = [
  "Kalau [nama] punya jasa, barang buat dijual, atau pengumuman penting di {daerah}, bagi ke sini saja ya. Saya bantu sebarkan supaya makin banyak yang tahu!",
  "Mau promosi jasa atau usaha [nama] di {daerah}? Atau mungkin mau buka lapak jual-beli? Kabari saya ya, saya senang bisa bantu Kakak terhubung dengan komunitas di sini.",
  "Ada pengumuman atau mau promosi sesuatu di {daerah}? [nama] bisa langsung bagi di sini. Saya siap bantu sebarkan untuk Kakak!",
  "Apapun yang ingin [nama] promosikan, dari kuliner sampai jasa, bagikan saja di sini ya. Saya senang sekali bisa bantu [nama] terhubung dengan warga {daerah}.",
  "Ingin usaha atau jasa [nama] makin dikenal banyak orang di {daerah}? Saya siap bantu hubungkan dengan komunitas. Ayo, mau mulai promosi apa hari ini?",
  "Kalau [nama] punya info atau mau promosi jasa/jualan di {daerah}, kasih tahu saya saja ya. Saya senang bisa jadi perantara buat komunitas kita.",
  "Ada kost kosong atau mau jual barang di {daerah}? Boleh banget promosi di Goona. Saya siap bantu [nama] untuk posting sekarang!",
  "Saya siap bantu [nama] mempromosikan apapun di Goona agar bisa terhubung dengan warga {daerah} lainnya. Seru kan? Mau mulai posting apa hari ini?",
  "Butuh bantuan untuk promosi usaha atau berbagi info penting di {daerah}? Goona tempatnya. Langsung saja ya, [nama]!",
  "Suka berbagi info atau mau promosi barang/jasa di {daerah}? Saya siap bantu [nama] di sini supaya makin banyak yang lihat.",
  "Kalau [nama] punya pengumuman penting atau mau promosi usaha di {daerah}, kasih tahu saya ya. Saya senang bisa bantu sebarkan.",
  "Mau buka lapak jual-beli atau cari penyewa kost di {daerah}? [nama] bisa posting di sini. Saya siap bantu!",
  "Ada jasa atau barang yang mau [nama] tawarkan di {daerah}? Langsung kasih tahu saya saja, nanti saya bantu.",
  "Saya siap bantu [nama] mempromosikan apa pun di {daerah} agar makin dikenal. Mau mulai posting sekarang?",
  "Ingin berbagi info penting atau promosi di {daerah}? [nama] bagi saja ke saya, nanti saya bantu sebarkan.",
  "Ada info loker atau pengumuman penting yang mau [nama] bagikan di {daerah}? Kabari saya ya.",
  "Mau promosi usaha [nama] di {daerah}? Saya siap bantu agar komunitas kita makin tahu.",
  "Kalau [nama] punya info menarik buat dibagikan di {daerah}, kasih tahu saya ya. Senang sekali bisa bantu.",
  "Butuh bantuan promosi jasa [nama] di {daerah}? Langsung bilang saja ya, nanti saya bantu.",
  "Ada kost atau kontrakan kosong di {daerah}? [nama] bagikan saja di sini, saya siap bantu.",
  "Saya siap bantu [nama] sebarkan promosi apa saja di {daerah}. Ayo, mau mulai dari mana?",
  "Kalau [nama] punya barang untuk dijual di {daerah}, kasih tahu saya saja ya. Saya bantu sebarkan.",
  "Mau berbagi info komunitas di {daerah}? [nama] langsung saja sampaikan ke saya.",
  "Ingin usaha [nama] makin sukses di {daerah}? Yuk, promosi di Goona. Saya siap bantu.",
  "Ada pengumuman mendesak atau info penting di {daerah}? [nama] bagi ke sini saja ya.",
  "Apapun yang [nama] mau promosikan di {daerah}, saya siap bantu sebarkan.",
  "Senang bisa bantu [nama] mempromosikan usaha di {daerah}. Mau posting apa hari ini?",
  "Ada jasa yang mau [nama] tawarkan di {daerah}? Bilang saja ke saya.",
  "Saya siap bantu [nama] terhubung dengan komunitas di {daerah} lewat promosi Kakak.",
  "Kalau [nama] mau berbagi info atau jualan di {daerah}, saya selalu siap membantu."
];
